### ISSUE TITLE
[BUG]  Navbar buttons not working on click

### ISSUE THREAD

**Issue by Mihir2423** [devs-in-tech/DevsInTech#101]
### Is there any existing issue for this?

- [X] I have searched the existing issues

### Description

When clicking on nav items, the page doesn't scroll to that section, I want to add the navigation feature to smoothly scroll to the particular section when clicked.

Can I solve this issue under GSSOC '23?

### What browser are you seeing the problem on?

Chrome

**Comment by himanshu1221** [comment]
Hey there some one is already working on this issue you can find another
You can refer to #74 for the same
