### ISSUE TITLE
Dark and Light Mode 

### ISSUE THREAD

**Issue by arin-paliwal** [devs-in-tech/DevsInTech#102]
### Description

I have created an issue to propose the implementation of dark and light mode support for the project. This feature will enhance the user experience by allowing them to switch between different color themes based on their preferences or the ambient lighting conditions.

**Comment by arin-paliwal** [comment]
Assign this issue to me
This feature will greatly enhance the project's usability and cater to a wider range of users' preferences. I look forward to working on the implementation and collaborating with the community on this exciting addition to the project.

**Comment by himanshu1221** [comment]
Hey @arin-paliwal this issue is already in discussion check out #81
