### ISSUE TITLE
[Feature] Add an image next to Landing Page Description

### ISSUE THREAD

**Issue by abhinav-m22** [devs-in-tech/DevsInTech#104]
### Description

Add an image on the Home Page besides the Header/Description, to make the page look more active. 
The image will be related to Tech or Community.
Without the image, the landing page looks a bit empty and bug-proned.

### Screenshots

Attaching a screenshot for reference:

<img width="944" alt="image" src="https://github.com/devs-in-tech/DevsInTech/assets/113239388/03d52d75-bf9e-473b-83d3-f8667ec64065">

### Additional Information

I want to work on these issue.
Please assign me the task under GSSoC'23.

**Comment by syedawanya18** [comment]
I want to work on this issue
Pleasure Assign so that I can show my skills under GSSoC'23.

**Comment by himanshu1221** [comment]
Hy @syedawanya18 
This issue has already been stated in #84 
you can share your ideas there we will review them and they seem relevant we will assign you for the same
