### ISSUE TITLE
[style]: UI Improvement

### ISSUE THREAD

**Issue by babitarit** [devs-in-tech/DevsInTech#107]
### What's the style idea?

We need to improve  the color of text as because this color  is not clearly visible so its difficult for the users to read it

### Add screenshots

Add screenshots
![Screenshot (96)](https://github.com/devs-in-tech/DevsInTech/assets/118760765/fd56600b-1311-4290-b697-f7653bd0b260)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by arin-paliwal** [comment]
Assign it to me, I can fix it

**Comment by himanshu1221** [comment]
Hey @arin-paliwal @babitarit  someone is already working on this issue kindly check this out #69
