### ISSUE TITLE
[style]: Add Icons to Button for Enhanced Visual Appeal

### ISSUE THREAD

**Issue by manasi-jain** [devs-in-tech/DevsInTech#108]
### What's the style idea?

Currently, the button component in the project lacks visual appeal. I would like to enhance its design by adding icons to the button. This will not only make it look more attractive but also provide visual cues to users.

If you think it is legit then do assign me the issue under GSSoC '23

### Add screenshots

- Before
<img width="434" alt="Screenshot 2023-05-21 at 11 53 02 PM" src="https://github.com/devs-in-tech/DevsInTech/assets/83013408/01bdd315-cb72-4e31-a62a-0a047c7e4945">

- After
<img width="432" alt="Screenshot 2023-05-21 at 11 54 25 PM" src="https://github.com/devs-in-tech/DevsInTech/assets/83013408/f5b6f7b6-f440-4962-8a63-5e5bf589b561">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by himanshu1221** [comment]
Seems relevant to me 
assigning you @manasi-jain 
good luck :rocket:
