### ISSUE TITLE
[UI] <Added Hover Effect and buttons>

### ISSUE THREAD

**Issue by arin-paliwal** [devs-in-tech/DevsInTech#109]
### Description

Changes proposed
Made the navbar sticky on the y-axis scroll by adding the sticky class to the outermost div element and setting top-0 and bg-black classes for styling.

Updated the structure of the navbar by moving the image and text into a div with the flex and items-center classes to align them horizontally.

Added a hover effect to the navbar links by modifying the className of the Link component to include text-white hover:text-[#194fbc] duration-500.

Added the "Join Us" button to the list

### Screenshots

![239738484-fa992b88-96ec-4153-8c87-6bd21216d40a](https://github.com/devs-in-tech/DevsInTech/assets/100232893/062090c7-fd17-420d-b52f-36853a9e6d1b)

**Comment by himanshu1221** [comment]
Hey there this is not required in the design 
someone is already working on the underline effect in the navbar check this out #98
