### ISSUE TITLE
[Improve FAQ Section]

### ISSUE THREAD

**Issue by sujitmemane** [devs-in-tech/DevsInTech#110]
### What would you like to share or ask?

Hello, Maintainer! 👋🏼
I am [Sujit Memane](https://thesujitmemane.vercel.app/), a front-end React developer with expertise in creating visually stunning user interfaces. I am currently working on enhancing the FAQ section of a landing page. My aim is to implement a feature where only one question can be opened at a time, automatically closing the answers to other questions when one is opened.

In this regard, I have developed a sample project that showcases the desired behavior. You can access the project [Accordion Project](https://faq-accordion-three-eta.vercel.app/).
By incorporating this functionality into the FAQ section, users will enjoy a more streamlined and intuitive experience while browsing through the frequently asked questions. I encourage you to explore the sample project to see firsthand how this feature enhances the usability of the FAQ section.

Looking forward to the opportunity!\

**Comment by himanshu1221** [comment]
Hey @sujitmemane 
Can you explain what kind of changes will you be doing because someone is already working on the same #77 if your changes are different then we will review and assign

**Comment by sujitmemane** [comment]
This is a same issue

**Comment by himanshu1221** [comment]
> This is a same issue 

Then you folks can collaborate on the same issue 

Closing this one
