### ISSUE TITLE
[style]: About Us Component 

### ISSUE THREAD

**Issue by Hemant2335** [devs-in-tech/DevsInTech#117]
### What's the style idea?

We need to improve  the about component and I have some ideas for that like

-> we can wrap them in a Wrapper 
-> And can decrease the gap between the stats
-> Also a scroll Effect can also be added 

therefore I request  you to please assign this task to me under GSSOC'23

Thank you !

### Add screenshots

Add screenshots
![Screenshot (64)](https://github.com/devs-in-tech/DevsInTech/assets/85656999/38e57471-8144-47b4-a430-e2a85601641a)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by himanshu1221** [comment]
Looks relevant to me
assigning you @Hemant2335 :rocket:

**Comment by Hemant2335** [comment]
Thank you It will be done Soon

**Comment by AbhiPatel10** [comment]
@Hemant2335 are you working on it ?
