### ISSUE TITLE
[Docs]: add readme badges

### ISSUE THREAD

**Issue by S-ishita** [devs-in-tech/DevsInTech#119]
### what's wrong in the documentation?

We need to add readme badges

### Add screenshots

![badges](https://github.com/devs-in-tech/DevsInTech/assets/104543751/15b4184d-3425-4046-961a-560adbbc26d8)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by himanshu1221** [comment]
Go for it @S-ishita assigning you :rocket:
