### ISSUE TITLE
[Feature] Linking navigation options to other sections

### ISSUE THREAD

**Issue by md-abid-hussain** [devs-in-tech/DevsInTech#120]
### Description

The link in navigation bar is not linked to the section. Clicking it doesn't lead to desired section.

### Screenshots

![Screenshot (50)](https://github.com/devs-in-tech/DevsInTech/assets/101964499/d678b4c6-45ef-476d-8968-a39dff3e811e)

**Comment by himanshu1221** [comment]
go for it @md-abid-hussain and make sure that it scrolls smoothly :rocket:

**Comment by md-abid-hussain** [comment]
It seems this issue has been resolved. See https://github.com/devs-in-tech/DevsInTech/commit/27555d9cd2ffda30e46c22627a4208c4c435dc68

**Comment by himanshu1221** [comment]
> It seems this issue has been resolved. See https://github.com/devs-in-tech/DevsInTech/commit/27555d9cd2ffda30e46c22627a4208c4c435dc68

Woops my bad sorry for the inconvenience ig i missed it
