### ISSUE TITLE
[OTHER] Add a custom 404 Not found page

### ISSUE THREAD

**Issue by Sukhendu2002** [devs-in-tech/DevsInTech#124]
### What would you like to share or ask?

Add a custom 404 Not Found page

![image](https://github.com/devs-in-tech/DevsInTech/assets/76804228/2f471d24-308c-4380-956c-850d37a47c22)

**Comment by priddhesh** [comment]
I would like to contribute to this issue.Can you please ellaborate the issue?

**Comment by himanshu1221** [comment]
Assigin in chronological order go for it @Sukhendu2002  :rocket:

**Comment by Sukhendu2002** [comment]
@himanshu1221, Can i do this
![image](https://github.com/devs-in-tech/DevsInTech/assets/76804228/5fafb1a3-fb01-4938-8546-c9986103c86f)

**Comment by AbhiPatel10** [comment]
Yes Looks good, Generate PR
