### ISSUE TITLE
Adding background image 

### ISSUE THREAD

**Issue by ManishaSwain8** [devs-in-tech/DevsInTech#125]
### What would you like to share or ask?

website looks too simple ,adding a background image can make it attractive. 
![Screenshot (46)](https://github.com/devs-in-tech/DevsInTech/assets/96622693/6a083d77-f9e1-4278-99b8-93a4304c7439)
for example,
 If want change, do assign it to me under GSSOC 2023 .  :)

**Comment by khushi767** [comment]
Please assign me this issue under GSSOC'23

**Comment by md-abid-hussain** [comment]
Background image is only appearing to a specific length. It makes the site less attractive. Please make the background cover the the whole height of the site.
