### ISSUE TITLE
update navbar animation on phone screen

### ISSUE THREAD

**Issue by Sandeep0306** [devs-in-tech/DevsInTech#128]
### What's the style idea?

Subject: Contribution Proposal: update navbar animation on mobile screen

Hello ,

I would like to contribute to your open-source project under GSSOC'23 & i will update the navbar animation on mobile screen & to make navbar sticky . I believe this enhancement will improve user experience and ease navigation. I am eager to collaborate with the project.

Thank you .

Best regards,
Sandeep Biswal

### Add screenshots

Add screenshots
![Screenshot 2023-05-23 144441](https://github.com/devs-in-tech/DevsInTech/assets/112690853/4f723c4e-004f-4a1d-b649-eec7f46399b8)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by himanshu1221** [comment]
Hey @Sandeep0306
It would be great if you share any videos or GIFs so we can understand better what kind of animation you want to add

**Comment by itsPriyanshuhere** [comment]
Saw this issue was open 5 days ago but no one was assigned. Can I implement an animation of the navbar for the mobile version of the website? The link to the animation: https://www.behance.net/collection/204363551/NAVBAR.
Could you please assign me under gssoc label?

**Comment by KamalSritha-04** [comment]
Can you please assign me this issue under GSSOC'23?

**Comment by AbhiPatel10** [comment]
> Saw this issue was open 5 days ago but no one was assigned. Can I implement an animation of the navbar for the mobile version of the website? The link to the animation: https://www.behance.net/collection/204363551/NAVBAR. Could you please assign me under gssoc label?

We do not need animation like this

**Comment by AbhiPatel10** [comment]
@Sandeep0306 are you working on it ?

**Comment by Susmita-Dey** [comment]
@Sandeep0306 Kindly do it for mobile only as there are 2 more people working on desktop version
