### ISSUE TITLE
[Feature] Adding animations to Hero Section.

### ISSUE THREAD

**Issue by kartikayasija** [devs-in-tech/DevsInTech#129]
### Description

Animations to Hero Section with Particle.js. It will improve UI of site.

### Screenshots

<img width="948" alt="image" src="https://github.com/devs-in-tech/DevsInTech/assets/115306535/c1012746-77bb-4b95-b5f5-8ee5a85b6b80">

### Additional Information

Please assign me this issue under GSSOC'23

**Comment by khushi767** [comment]
Please assign me this issue under GSSOC'23

**Comment by kartikayasija** [comment]
@himanshu1221 Please assign me this issue.

**Comment by AbhiPatel10** [comment]
@kartikayasija Go ahead
