### ISSUE TITLE
[Feature] Add a copyright section at the footer

### ISSUE THREAD

**Issue by abhinav-m22** [devs-in-tech/DevsInTech#130]
### Description

Below the footer, adding a copyright section with a dynamic year can make the website look more formal. 
A function needs to be added in order to fetch the current year and display the same.

### Screenshots

<img width="944" alt="image" src="https://github.com/devs-in-tech/DevsInTech/assets/113239388/a11ec17a-8b99-4f47-87c5-0f3682204283">

### Additional Information

I want to work on these adding this feature.
Please assign me the task under GSSoC'23.

**Comment by SagarSharma2809** [comment]
I think It is added now, just checked the website

**Comment by abhinav-m22** [comment]
> I think It is added now, just checked the website

Ohh yes.. It'present, but the font color is same as the background and hence it is not visible.

<img width="944" alt="image" src="https://github.com/devs-in-tech/DevsInTech/assets/113239388/a11ec17a-8b99-4f47-87c5-0f3682204283">

<img width="930" alt="image" src="https://github.com/devs-in-tech/DevsInTech/assets/113239388/02fe9e9a-561a-4eaa-ad9b-a87b45ea97b5">

Also the value of the year is hard-coded to 2023. In the issue I am talking about adding a dynamic year value which will be fetched from a Javascript function. So no need to hard-code it everytime.

Please look into it once.

**Comment by abhinav-m22** [comment]
Hey @SagarSharma2809 ...
I have added a PR - #134 
Please have a look.

**Comment by himanshu1221** [comment]
Hey @abhinav-m22 in order to raise a PR firstly you should get your issue reviewed by the maintainer before making any PR
The issue looks relevant to me assigning you @abhinav-m22

**Comment by himanshu1221** [comment]
closing as completed
