### ISSUE TITLE
[Update Docs]: typo fix 

### ISSUE THREAD

**Issue by SagarSharma2809** [devs-in-tech/DevsInTech#132]
### what's wrong in the documentation?

We need to correct the typo "some linke minded people" to "some like minded people". In the ReadMe doc at line no. 9th. I can correct that. It is a very small issue but important since everyone read read me doc and it can create confusion and looks unprofessional. 

### Add screenshots

Add screenshots
![image](https://github.com/devs-in-tech/DevsInTech/assets/108415064/8a37852f-d239-49fa-b3ee-de2b9268bae0)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by himanshu1221** [comment]
assigning you @SagarSharma2809 :rocket:
