### ISSUE TITLE
[Feature] Adding Pre Loader page  [GSSOC 2023]

### ISSUE THREAD

**Issue by ManishaSwain8** [devs-in-tech/DevsInTech#133]
### Description

Adding a pre loader page can make it more attractive and fun website.
If this feature is needed ,
Do assign it to me under GSSOC 2023 !  :)

**Comment by khushi767** [comment]
Please assign me this issue under GSSoC'23, thank you.

**Comment by khushi767** [comment]
> Anyone is working on this issue @ManishaSwain8 or @khushi767 ?

i have already added added pull request after making chaanges

**Comment by AbhiPatel10** [comment]
> > Anyone is working on this issue @ManishaSwain8 or @khushi767 ?
> 
> i have already added added pull request after making chaanges

Which PR can you mention here ?

**Comment by khushi767** [comment]
> > > Anyone is working on this issue @ManishaSwain8 or @khushi767 ?
> > 
> > 
> > i have already added added pull request after making chaanges
> 
> Which PR can you mention here ?

#153

**Comment by ManishaSwain8** [comment]
I have not been assigned this issue yet so I am not able to work on it 
@AbhiPatel10 
@himanshu1221

**Comment by Susmita-Dey** [comment]
Hey @ManishaSwain8 Go ahead
