### ISSUE TITLE
[BUG] Updating text in accordion 

### ISSUE THREAD

**Issue by himanshu1221** [devs-in-tech/DevsInTech#136]
### Is there any existing issue for this?

- [X] I have searched the existing issues

### Description

Will update the text of accordion as its not up to mark 

### What browser are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

**Comment by Vyom-V** [comment]
could you assign this issue to me? thank you :)

**Comment by himanshu1221** [comment]
> could you assign this issue to me? thank you :)

Hey @Vyom-V some issues are allotted for maintainer
So you can or create one for you 😉
