### ISSUE TITLE
[Feature] Responsiveness of the Events Cards

### ISSUE THREAD

**Issue by kumarankit999** [devs-in-tech/DevsInTech#141]
### Description

If we can see below, In the images below it is not responsive . There should be a link which is attached to this card ,by that if we click on the event we can be redirected to the event page link.

### Screenshots

![image](https://github.com/devs-in-tech/DevsInTech/assets/111564362/d6a985e9-52c3-42c5-8357-daf2aec80e6d)

### Additional Information

We can add the link in a href tag

**Comment by himanshu1221** [comment]
It is just  static card rn we don't have any recordings of these sessions 
so closing as not planned

**Comment by kumarankit999** [comment]
After this we can add those events, which have it's event page, otherwise we can remove this feature at all
