### ISSUE TITLE
[style]: social media handles icon disappearing in light mode 

### ISSUE THREAD

**Issue by md-abid-hussain** [devs-in-tech/DevsInTech#143]
### What's the style idea?

In dark mode the icons are appearing fine. However in case of light mode they disappear as their color matches with background. 

It can be fixed either by adding the light mode theme to the whole site which is quite time consuming or changing the color of the icon. 

For the time being changing color of icon will be the good option. 

## Dark Mode
![Screenshot_20230523_232339_Brave](https://github.com/devs-in-tech/DevsInTech/assets/101964499/2ad99bb1-59c8-4ef9-a73f-09a958e5f7ed)

## Light Mode
![Screenshot_20230523_232329_Brave](https://github.com/devs-in-tech/DevsInTech/assets/101964499/71fd2b23-0356-43ca-adfe-4cdee6ae33fa)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by himanshu1221** [comment]
hey @md-abid-hussain someone is already working on this only #69
