### ISSUE TITLE
Adding Hover Effect(Gssoc'23)

### ISSUE THREAD

**Issue by shwetazade27** [devs-in-tech/DevsInTech#144]
### What would you like to share or ask?

Hover effect can be added on these cards and also I can work on dummy text 
![419_new](https://github.com/devs-in-tech/DevsInTech/assets/84389800/2cc7a14b-4cc0-45d6-b4c2-4cfa2cfba94f)

### Additional information

If you deem it appropriate, I would greatly appreciate it if you could kindly assign this issue to me.

**Comment by himanshu1221** [comment]
Hey @shwetazade27 this issue has already been stated kindly check #90

**Comment by shwetazade27** [comment]
Thankyou for reply
