### ISSUE TITLE
[Docs]: add contributor graph

### ISSUE THREAD

**Issue by S-ishita** [devs-in-tech/DevsInTech#149]
### what's wrong in the documentation?

We need to add  add contributor graph in readme

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CBID2** [comment]
I’ll do it @S-ishita! :)

**Comment by S-ishita** [comment]
Please assign this issue to me

**Comment by prnvtripathi** [comment]
@CBID2, Please look into solving some other issue as @S-ishita has opened it.

**Comment by prnvtripathi** [comment]
@S-ishita, assigning this issue to you.

**Comment by S-ishita** [comment]
someone already added it @prnvtripathi
