### ISSUE TITLE
[BUG] Unknown margin while adding Dark Mode.

### ISSUE THREAD

**Issue by Nikhil1017** [devs-in-tech/DevsInTech#150]
### Is there any existing issue for this?

- [X] I have searched the existing issues

### Description

Here is the link to the fork 
https://github.com/Nikhil1017/DevsInTech/tree/main
I have searched all the files and unable to solve this margin as shown in screenshot

### Screenshots

![image](https://github.com/devs-in-tech/DevsInTech/assets/115337705/cb679645-d1a1-4034-8afd-2b8fed4df626)

**Comment by himanshu1221** [comment]
Hey @Nikhil1017 as our team discussed we are not planning for dark mode so closing this issue
