### ISSUE TITLE
Collapse an Accordion when one accordion is open

### ISSUE THREAD

**Issue by Vijaykv5** [devs-in-tech/DevsInTech#151]
### Description

When a person clicks on Faq's , It Opens Up but when he clicks on another accordian, The current open one should close and other should opens up. 

### Screenshots

![Capture](https://github.com/devs-in-tech/DevsInTech/assets/94985341/c68c0764-3205-4b17-9a35-3dff09996a52)

**Two of them cannot Open simultaneously**

**Comment by himanshu1221** [comment]
Hey @Vijaykv5 someone is already working on this issue check out #77
