### ISSUE TITLE
[OTHER]: Footer update

### ISSUE THREAD

**Issue by shaikahmadnawaz** [devs-in-tech/DevsInTech#152]
### What would you like to share or ask?

Footer update, because footer content is not good, and alignments of elements in the footer are also not at correct position.

I will solve this issue, assign this to me.

![Screenshot (849)](https://github.com/devs-in-tech/DevsInTech/assets/96189881/729fad49-2915-4d77-996e-463da0794bee)

I'm in GSSOC'23

**Comment by himanshu1221** [comment]
Hey @shaikahmadnawaz this issue has already been stated kindly check #69

**Comment by shaikahmadnawaz** [comment]
> Hey @shaikahmadnawaz this issue has already been stated kindly check #69 

Okay
