### ISSUE TITLE
[Feature] Add hover effect on card items

### ISSUE THREAD

**Issue by Soulpurr** [devs-in-tech/DevsInTech#157]
### Description

I would like to add hover effect on card items as static cards are not that good looking.
![scrnli_25_05_2023_18-44-19](https://github.com/devs-in-tech/DevsInTech/assets/92094765/38bf88a3-3a82-4134-bbd2-a469592eb933)
 pls assign this to me under gssoc 23

**Comment by himanshu1221** [comment]
go for it @Soulpurr assigning you
