### ISSUE TITLE
[Feature] IMPROVE THE UI OF THE LANDING PAGE [GSSoC'23]

### ISSUE THREAD

**Issue by mohammadshaad** [devs-in-tech/DevsInTech#158]
### Description

I designed the new UI of the landing page of the DevsInTech community.

### Screenshots

It looks like this 
![DEVSINTECH](https://github.com/devs-in-tech/DevsInTech/assets/89409389/4d3f2283-9c3e-48f6-85ca-1a8956a397e4)

### Additional Information

Kindly assign me this issue as I am a GSSoC contributor

**Comment by mohammadshaad** [comment]
@himanshu1221 kindly assign me this issue

**Comment by himanshu1221** [comment]
Hey @mohammadshaad this issue has already been stated #107

**Comment by mohammadshaad** [comment]
But I have updated the landing page. There is difference in the issues. Kindly see

**Comment by himanshu1221** [comment]
Yes we know that kindly checkout the #138 for the same discussion
