### ISSUE TITLE
[style]: Add a custom scroll bar

### ISSUE THREAD

**Issue by harshit-002** [devs-in-tech/DevsInTech#159]
### What's the style idea?

Change the basic scroll bar to a custom stylish scroll bar.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by himanshu1221** [comment]
can you share any design @harshit-002

**Comment by harshit-002** [comment]
@himanshu1221 
<img width="958" alt="Screenshot 2023-05-27 114738" src="https://github.com/devs-in-tech/DevsInTech/assets/95224348/86190632-ec76-4155-810d-257f7e28e743">

<img width="956" alt="Screenshot 2023-05-27 115315" src="https://github.com/devs-in-tech/DevsInTech/assets/95224348/b88275ec-0fba-4fc8-8d26-0297f283a1e9">

**Comment by harshit-002** [comment]
@himanshu1221 
<img width="958" alt="Screenshot 2023-05-27 114738" src="https://github.com/devs-in-tech/DevsInTech/assets/95224348/abc9de4d-58ca-4bcc-8c33-c3dc986d773d">

<img width="956" alt="image" src="https://github.com/devs-in-tech/DevsInTech/assets/95224348/f9fa9b7e-4910-4086-9e05-30d2e406ca2b">

**Comment by himanshu1221** [comment]
Looks revant to mee assigning you @harshit-002
