### ISSUE TITLE
[BUG] <Navigation menu doesn't close after clicking link>

### ISSUE THREAD

**Issue by md-abid-hussain** [devs-in-tech/DevsInTech#160]
### Is there any existing issue for this?

- [X] I have searched the existing issues

### Description

After selecting any option from navigation the menu doesn't close. It remain open until we click on close button.
This problem rises only in smaller viewport.

### Screenshots

![Screenshot (53)](https://github.com/devs-in-tech/DevsInTech/assets/101964499/80e7a9c2-a9b1-4b26-bfd4-7ef0afe97e1a)

**Comment by himanshu1221** [comment]
Works fine on my machine

**Comment by md-abid-hussain** [comment]
It remain open until we close it

**Comment by himanshu1221** [comment]
got it assigning you @md-abid-hussain :rocket:
