### ISSUE TITLE
[Feature] Description about the website in the Home Page

### ISSUE THREAD

**Issue by prernadabi23** [devs-in-tech/DevsInTech#163]
### Description

There is no description of the website on the home page on top and the footer too.
I would like to take this issue as part of GSSOC'23.

### Screenshots

![Screenshot from 2023-05-26 15-33-39](https://github.com/devs-in-tech/DevsInTech/assets/104578155/fb55b1a2-6b74-4a60-b35f-bc8b052f59b6)

### Additional Information

To help people understand the website and its purpose, we can create a catchy headline. We'll also provide a brief description of the website, explaining its uses and the benefits it offers.

**Comment by himanshu1221** [comment]
hey @prernadabi23 this issue has already been resolve #116
