### ISSUE TITLE
[style]:  Font styling for mobile and Footer adjustment for larger screen

### ISSUE THREAD

**Issue by wisdom-egba** [devs-in-tech/DevsInTech#165]
### What's the style idea?

We need to improve the text spacing on the mobile view and also work on the footer section for a larger view 

### Add screenshots

Add screenshots
![dev2](https://github.com/devs-in-tech/DevsInTech/assets/99222194/5249f6fd-0cbe-4a5b-b504-df4870db0069)
![dev1](https://github.com/devs-in-tech/DevsInTech/assets/99222194/c3e9b3e8-1eae-4f41-bc18-b9f5d9ec7a77)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by himanshu1221** [comment]
you can proceed with text spacing, someone is already working with footer #69

**Comment by AbhiPatel10** [comment]
@wisdom-egba are you working on this issue ?
