### ISSUE TITLE
[Feature] Adding "Contact us" page

### ISSUE THREAD

**Issue by anirudhsalaria** [devs-in-tech/DevsInTech#167]
### Description

"Contact us" page will add more value to your website, as the clients who are surfing your website will be able to contact you directly.
The "Contact us" page will contain your linkedin, twitter and a text message box using which clients can send you the message directly.
For the text box, I will be using formspree. You can generate your own formspree link and I will add it to the backend, after this you will directly receive all the messages of your clients.
Rest I assure that you will get a good user interface.

**Comment by himanshu1221** [comment]
Hey @anirudhsalaria if someone wants to get in touch they can join our discord or social handle I don't feel there is need of specific contact us page
