### ISSUE TITLE
[style]: Making Navbar fixed

### ISSUE THREAD

**Issue by whiteknight16** [devs-in-tech/DevsInTech#168]
### What's the style idea?

Fix the navbar at the top even on scrolling for easier navigation

### Add screenshots

![Screenshot 2023-05-27 153055](https://github.com/devs-in-tech/DevsInTech/assets/111869559/2c099e5d-3c79-4946-ace5-eedb58c4a092)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by whiteknight16** [comment]
Kindly assign me this issue

**Comment by himanshu1221** [comment]
Hey @whiteknight16 this issue has already been stated check #172
