### ISSUE TITLE
[style]: Improving the UI in Mobile View

### ISSUE THREAD

**Issue by Vishalk91-4** [devs-in-tech/DevsInTech#169]
### What's the style idea?

The DevsInTech page in Mobile looks in first to have a lot of text, I could represent those texts with infographics so the page would look more attractive rather than a lot of texts at present

### Add screenshots

Add screenshots
Currently it looks with lot of text

![image](https://github.com/devs-in-tech/DevsInTech/assets/116670999/9b2c9a71-2414-4f45-b545-e99505ab5cbf)

@himanshu1221 could you please assign it to me under GSSOC23

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by prnvtripathi** [comment]
Can you share any design or made some work on this?

**Comment by Susmita-Dey** [comment]
Hey @Vishalk91-4 Kindly share some design which you have in your mind
