### ISSUE TITLE
[BUG] Website Content is repeative

### ISSUE THREAD

**Issue by arpitghura** [devs-in-tech/DevsInTech#170]
### Is there any existing issue for this?

- [X] I have searched the existing issues

### Description

The Content on the website is repeated like in the Hero section, a single paragraph is repeated three times. 
Similarly in FAQs section, All questions have same answer except the first question.

### Screenshots

![image](https://github.com/devs-in-tech/DevsInTech/assets/41796013/281841b8-b450-4e22-8995-fdf168d1f3a6)

![image](https://github.com/devs-in-tech/DevsInTech/assets/41796013/0ca3b41f-31c5-470d-b870-9bca697c7887)
The highlighted text is repeated.

### What browser are you seeing the problem on?

Chrome

**Comment by arpitghura** [comment]
I would like to work on this Issue under GSSOC'23

**Comment by himanshu1221** [comment]
Hey @arpitghura i am not able to recreate the issue that you have stated in hero section and repeated text in accordion has already been stated #136
