### ISSUE TITLE
Margin required in social icons section[Feature] <description>

### ISSUE THREAD

**Issue by HimanshuNarware** [devs-in-tech/DevsInTech#173]
### Description

social icons section icons need margin. it affecting the UI of the website , I want to work on this issue

### Screenshots

#screenshot
![50](https://github.com/devs-in-tech/DevsInTech/assets/83147410/ad029df0-6f3a-495d-a407-5cbb9718cc8f)

**Comment by himanshu1221** [comment]
I feel its a decent margin
