### ISSUE TITLE
[OTHER] : Improving code quality and removing warning

### ISSUE THREAD

**Issue by md-abid-hussain** [devs-in-tech/DevsInTech#178]
### What would you like to share or ask?

The list element missing or having same key prop. The key prop helps React efficiently identify and update individual elements within the list and thus improving rendering performance and avoiding potential issues.

It is also recommended to add key prop in list element

![Screenshot (54)](https://github.com/devs-in-tech/DevsInTech/assets/101964499/85f6bfa8-b54e-4ed5-8239-b7e42b04bdec)

**Comment by himanshu1221** [comment]
Hey @md-abid-hussain looks relevant to me go for it :rocket:
