### ISSUE TITLE
[Feature] Change Hero Section

### ISSUE THREAD

**Issue by kartikayasija** [devs-in-tech/DevsInTech#179]
### Description

The Hero section looks very simple, it should be attractive.
I will add gif or vector to the hero section or add some animation to make it look attractive.

### Additional Information

Please assign this issue to me.

**Comment by prnvtripathi** [comment]
What changes in specific you'll do the hero section.

**Comment by kartikayasija** [comment]
@prnvtripathi I'll try to improve the design, add a good gif or vector and some animation effects like particle.js

**Comment by prnvtripathi** [comment]
@kartikayasija Do you have any design? Like what your end result might look like.

**Comment by KamalSritha-04** [comment]
Can you assign me this issue under gssoc'23?

**Comment by Susmita-Dey** [comment]
Hey @kartikayasija Can you show us some design which you have in your mind?
