### ISSUE TITLE
[Docs]: Add a section for GSSoC’23

### ISSUE THREAD

**Issue by CBID2** [devs-in-tech/DevsInTech#180]
### what's wrong in the documentation?

We need to add some special rules for GSSOC members in the Contributing file. Something like:
“Note: If you’re a GSSOC member, please check the _I am a GSSOC’23 Contributor_ checkbox in the issue template. **Do not create the pull request until you have confirmed with the maintainers that you are participating in this program**

I have done this for the LinksHub project and it has made distinguishing GSSoC contributors from regular ones so much easier. (Note: I will raise an issue about the checkbox described in my example).

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CBID2** [comment]
I will work on this issue

**Comment by himanshu1221** [comment]
Hey @CBID2 assigned you #181 so closing this
