### ISSUE TITLE
[OTHER] Add a GSSOC checkbox in issue template 

### ISSUE THREAD

**Issue by CBID2** [devs-in-tech/DevsInTech#181]
### What would you like to share or ask?

Even though GSSOC labels are placed on raised issues, I think it would be also beneficial to add a GSSOC checkbox to the issue template(I talk about this more in [this issue](https://github.com/devs-in-tech/DevsInTech/issues/180)). I’ve implemented this approach as a maintainer for LinksHub, and it made GSSOC PRs and issues more distinguishable.

**Comment by himanshu1221** [comment]
Looks relevant to me go ahead @CBID2 assigning you :rocket:

**Comment by CBID2** [comment]
> @CBID2  can i work on this issue

Hi @Bhanuteja01! I got started on it already

**Comment by Bhanuteja01** [comment]
Ok @CBID2

**Comment by CBID2** [comment]
> Ok @CBID2 

I'm open to your feedback on it @Bhanuteja01! :) Reviewing PRs is another skill worth learning in open source.
