### ISSUE TITLE
[style]: Making nav bar fixed is causing problem

### ISSUE THREAD

**Issue by md-abid-hussain** [devs-in-tech/DevsInTech#182]
### What's the style idea?

Making header fixed to top causes overlap problem with events card.
Instead of making header fixed to top we can use it show till hero section.
If the navigation bar extend to whole site then there is no purpose of the button which take us to the top of the website

### Add screenshots

Add screenshots
![Screenshot (57)](https://github.com/devs-in-tech/DevsInTech/assets/101964499/52cc7818-0496-4466-a7af-8f666beb696f)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by himanshu1221** [comment]
this issue looks relevant to me assigning you @md-abid-hussain
