### ISSUE TITLE
Light and Dark Theme Toggling is not present in Navbar

### ISSUE THREAD

**Issue by mrgulrez** [devs-in-tech/DevsInTech#184]
### Description

"Light and Dark Theme Toggling" feature in a webpage offers improved user experience, accessibility, reduced eye fatigue, energy efficiency, aesthetic appeal, personalization, and compatibility with other apps. By providing this feature, web developers can cater to various user preferences and create a more inclusive and engaging browsing experience.

### Screenshots

<img width="1920" alt="ss" src="https://github.com/devs-in-tech/DevsInTech/assets/97864586/546db18d-1fbf-4586-8ea9-e640cf76317e">

**Comment by himanshu1221** [comment]
Hey @mrgulrez we dont have any light theme in our website
