### ISSUE TITLE
[BUG] Missing FAQ link in Navbar

### ISSUE THREAD

**Issue by abhi03ruchi** [devs-in-tech/DevsInTech#185]
### Is there any existing issue for this?

- [X] I have searched the existing issues

### Description

The FAQ section link is not present in the navbar . 

I want to add FAQ section link also to the navbar. So that users can directly access the FAQ section in case of any doubts. 

### Screenshots

Currently
<img width="428" alt="Screenshot 2023-05-30 at 6 47 34 AM" src="https://github.com/devs-in-tech/DevsInTech/assets/105661636/839ec22f-e888-43f2-8010-6d11f32fe28c">

### Any additional information?

Plz assign this task to me under gssoc'23.

### What browser are you seeing the problem on?

Safari

**Comment by himanshu1221** [comment]
Looks relevant to me go ahead @abhi03ruchi assigning you :rocket:
