### ISSUE TITLE
[BUG] The Scrolling up Button Going behind 

### ISSUE THREAD

**Issue by vishnubansal001** [devs-in-tech/DevsInTech#188]
### Is there any existing issue for this?

- [X] I have searched the existing issues

### Description

In the mobile view of the website's landing page the scrolling up button is going behind the cards of the latest events section which is shown in the screenshots attached below:

### Screenshots

![2023-05-30 (8)](https://github.com/devs-in-tech/DevsInTech/assets/101445306/91c19f3e-8bc9-4d6d-941c-2ab299ca1cb6)
![2023-05-30 (9)](https://github.com/devs-in-tech/DevsInTech/assets/101445306/61bf8a17-124f-4e30-8d04-6d35f11902ce)

### Any additional information?

I am a GSSOC'23 contributor 
I want to resolve this issue please allow me to resolve this issue

**Comment by prnvtripathi** [comment]
@vishnubansal001 Thank you for opening this issue. You can go forward to work on it.

**Comment by KamalSritha-04** [comment]
Is this issue still open, Can I please get assigned to this issue under GSSOC'23?

**Comment by AbhiPatel10** [comment]
@vishnubansal001 are you working on it or i should assign to someone ?

**Comment by AbhiPatel10** [comment]
@KamalSritha-04 you can go ahead, assigning you
