### ISSUE TITLE
🚀 [FEAT]: IMPROVE ACCESSIBILITY, BEST PRACTICES OF SITE

### ISSUE THREAD

**Issue by 0xabdulkhalid** [devs-in-tech/DevsInTech#191]
### Description

- There are several issues regarding accessibility and best practices which we must want to focus to build a well scalable web application
- As per my analysis, there are some many loopholes in codes. i need to work on improvement of this site which helps to get Better ranking in Google for this site

### Additional Information

- I'm would like to work on this issue, so kindly assign me under `gssoc23` label and `level2` label for making new changes in codebase
- Thank you & looking forward to contribute!

**Comment by 0xabdulkhalid** [comment]
Hello @prnvtripathi, I'm gonna work at `html` to improve accessibility & best practices of this site to get best Search Engine Optimization

**Comment by AbhiPatel10** [comment]
@0xabdulkhalid Looks relevant, go ahead

**Comment by 0xabdulkhalid** [comment]
The work has Done @AbhiPatel10, you can now check it out the PR!
