### ISSUE TITLE
[BUG] Events Hovering 

### ISSUE THREAD

**Issue by parthpathakpp1** [devs-in-tech/DevsInTech#192]
### Is there any existing issue for this?

- [X] I have searched the existing issues

### Description

When we hover on Latest Events In DevsInTech . While it's card gets over on the navbar . 

### Screenshots

https://github.com/devs-in-tech/DevsInTech/assets/85991449/086a9b50-a21a-4d0e-9a19-de940ac2bef9

### What browser are you seeing the problem on?

Chrome

**Comment by parthpathakpp1** [comment]
Can you assign me this issue under GSSOC'23 .

**Comment by prnvtripathi** [comment]
Go ahead and work on this issue. :)
