### ISSUE TITLE
[Feature] Footer Section 

### ISSUE THREAD

**Issue by parthpathakpp1** [devs-in-tech/DevsInTech#193]
### Description

Footer Section needs improvement . Currently it does not look good . 

### Screenshots

![DEVINTECFOOTERSECTION](https://github.com/devs-in-tech/DevsInTech/assets/85991449/5a0f109c-ddc0-458d-9de5-e43ed517ddab)

**Comment by prnvtripathi** [comment]
How do you plan on improving the footer? Do you have a design in mind?

**Comment by parthpathakpp1** [comment]
> How do you plan on improving the footer? Do you have a design in mind?


**Somewhat like this , definitely will make some changes **
![devintechfootersectiondemo](https://github.com/devs-in-tech/DevsInTech/assets/85991449/0f64326f-9197-4922-b01f-bd400cd38aaa)

**Comment by AbhiPatel10** [comment]
Do not change whole footer just change In current design

**Comment by Jay-Thoriya** [comment]
@AbhiPatel10  please, do let us know, what part in footer, you want us to re-design ?

https://github.com/devs-in-tech/DevsInTech/issues/193#issuecomment-1570635947

do we want this  footer design ?
