### ISSUE TITLE
[BUG] Adding the content to "Lorem ipsum..." of footer section

### ISSUE THREAD

**Issue by 1Shubham7** [devs-in-tech/DevsInTech#196]
### Is there any existing issue for this?

- [X] I have searched the existing issues

### Description

The footer section of the website has a para of "Lorem ipsum..". Proper info about the website should be given their. 

### Screenshots

Here is the current footer section:
![footer content](https://github.com/devs-in-tech/DevsInTech/assets/116020663/8f3b2713-3f60-46c3-bf7f-1acabcf4fad2)

### Any additional information?

Please assign me this issue under GSSoC'23

### What browser are you seeing the problem on?

Chrome

**Comment by 1Shubham7** [comment]
Please assign me this issue under GSSoC'23

**Comment by prnvtripathi** [comment]
Go on @1Shubham7, start working on it.

**Comment by 1Shubham7** [comment]
@prnvtripathi  Thanks  a lot. I will surely not disappoint you.
