### ISSUE TITLE
Want to add answers to FAQs

### ISSUE THREAD

**Issue by P766-spec** [devs-in-tech/DevsInTech#198]
### Description

Hello, @prnvtripathi , want to answer all FAQs, if you allow me some specific content, I am a GSSOC'23 contributor.
If you feel it will be valuable and helpful to your project, then please assign me with the same.

Thank you!

**Comment by prnvtripathi** [comment]
Go ahead, assigning this to you.

**Comment by AbhiPatel10** [comment]
@P766-spec This issue is already generated by @himanshu1221 and he is working on it
