### ISSUE TITLE
[OTHER] Completing FAQs

### ISSUE THREAD

**Issue by Piyush-Gambhir** [devs-in-tech/DevsInTech#199]
### What would you like to share or ask?

The FAQs (Frequently Asked Questions) section of our open-source project currently contains placeholder text (Lorem Ipsum) and requires completion. To enhance user experience and provide helpful information, we need assistance in completing this section.

Please assign this issue to me under GSSOC 2023.

## Screenshots
![image](https://github.com/devs-in-tech/DevsInTech/assets/90608533/e62e648c-ac12-4e52-b62e-9dd08323369b)

**Comment by prnvtripathi** [comment]
@Piyush-Gambhir, there's already an issue opened related to this problem.
Please lookout for any other bugs and enhancements. Happy Contributing :)
