### ISSUE TITLE
Home page ui improvement. Button, text size, navbar

### ISSUE THREAD

**Issue by ojasaklechayt** [devs-in-tech/DevsInTech#200]
### What's the style idea?

Details:
1. Button Design Improvement.
2. Text Size Deceased.
3. Navbar Names Hover Improvement.
4. Content added for " What is DevsInTech Community? ".

Can you please assign me this tasks under GSSOC'23

### Add screenshots

Before:
![image](https://github.com/devs-in-tech/DevsInTech/assets/90605717/66f09ec1-f892-410a-96aa-9c0861ad3461)
![image](https://github.com/devs-in-tech/DevsInTech/assets/90605717/94b21c50-7a10-46cf-9a25-87d86320d9ae)

After:
![image](https://github.com/devs-in-tech/DevsInTech/assets/90605717/6043f620-f5ab-46ff-9672-6e87bd05cd89)
![image](https://github.com/devs-in-tech/DevsInTech/assets/90605717/e5e7cb21-60b1-4c85-b7a3-b493620c5258)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by prnvtripathi** [comment]
@ojasaklechayt Thank you for raising this issue, go forward, I'm assigning this to you.
