### ISSUE TITLE
[BUG] Go To Top Button Covers Link in Footer

### ISSUE THREAD

**Issue by ManasMadan** [devs-in-tech/DevsInTech#201]
### Is there any existing issue for this?

- [X] I have searched the existing issues

### Description

The Go to Top Button Covers the footer links when scrolled to bottom of page

### Screenshots

<img width="950" alt="image" src="https://github.com/devs-in-tech/DevsInTech/assets/84731321/b2de492d-ed67-408d-8044-8a946eb1834a">

### Any additional information?

This could be fixed by moving the button a little bit lower.

### What browser are you seeing the problem on?

Chrome

**Comment by ManasMadan** [comment]
@prnvtripathi Please assign me this issue under GSSoC 23

**Comment by prnvtripathi** [comment]
@ManasMadan Thank you for raising this issue. Go forward, I'm assigning this to you.

**Comment by ManasMadan** [comment]
@prnvtripathi Please review the PR #211, Meging that closes this issue as completed
