### ISSUE TITLE
[BUG] Adding proper answer to "What is DevsInTech Community?" [GSSoC'23]

### ISSUE THREAD

**Issue by 1Shubham7** [devs-in-tech/DevsInTech#207]
### Is there any existing issue for this?

- [X] I have searched the existing issues

### Description

The homepage of the website has a section of What is DevsInTech Community?  But answer is "Lorem ipsum". I can  create a proper answer for that.

### Screenshots

screenshot:
![answer](https://github.com/devs-in-tech/DevsInTech/assets/116020663/d220b138-3f1f-4b57-b9a8-284943a273ca)

### Any additional information?

Please assign me this issue under GSSoC'23

### What browser are you seeing the problem on?

Chrome

**Comment by 1Shubham7** [comment]
Please assign me this issue under GSSoC'23

**Comment by AbhiPatel10** [comment]
Which content will you add ?

**Comment by 1Shubham7** [comment]
@AbhiPatel10 I think I understand the mission the DevsInTech website, I can add my own answer or if you wish, you can let me know which answer to add.

**Comment by 1Shubham7** [comment]
Please assign me the issue, You can check and not accept the PR if you think the content is not good enough

**Comment by AbhiPatel10** [comment]
Okay Go ahead

**Comment by 1Shubham7** [comment]
Thank you @AbhiPatel10 . I will surely not disappoint you.

**Comment by 1Shubham7** [comment]
@AbhiPatel10 I think I have written a good and short answer. Can you please check it out.
