### ISSUE TITLE
Add contact Us page 

### ISSUE THREAD

**Issue by Nikita110602** [devs-in-tech/DevsInTech#209]
### Description

I want to add a contact us page in this project to make this project more user interacting. 

### Screenshots

![Screenshot (57)](https://github.com/devs-in-tech/DevsInTech/assets/111515819/f8c6bb3e-efcb-4103-97f0-d4af9ede28bc)

**Comment by Nikita110602** [comment]
pls assign me this issue . I want to work on this project.

**Comment by Susmita-Dey** [comment]
Hey @Nikita110602 contact us page is being assigned to someone else in #86 

Closing this as of now since it's a duplicate issue. If the issues persists for long, then you may reopen this issue again.
