### ISSUE TITLE
Home page ui improvement. text size, navbar

### ISSUE THREAD

**Issue by ojasaklechayt** [devs-in-tech/DevsInTech#210]
### What's the style idea?

Details:
1. Text Size Deceased.
2. Navbar Names Hover Improvement.
3. Content added for " What is DevsInTech Community? ".

Can you please assign me this tasks under GSSOC'23

### Add screenshots

Before:
![image](https://github.com/devs-in-tech/DevsInTech/assets/90605717/66f09ec1-f892-410a-96aa-9c0861ad3461)
![image](https://github.com/devs-in-tech/DevsInTech/assets/90605717/94b21c50-7a10-46cf-9a25-87d86320d9ae)

After:
![image](https://github.com/devs-in-tech/DevsInTech/assets/90605717/504c6088-2203-4f13-b89a-5ac265bb5bc3)
![image](https://github.com/devs-in-tech/DevsInTech/assets/90605717/e5e7cb21-60b1-4c85-b7a3-b493620c5258)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Add screenshots

Add screenshots

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by ojasaklechayt** [comment]
@prnvtripathi can I make pr now ? I have reverted the button changes.

**Comment by prnvtripathi** [comment]
Go ahead

**Comment by ojasaklechayt** [comment]
@prnvtripathi done ser
