### ISSUE TITLE
[Feature] ADDING A FEEDBACK SECTION

### ISSUE THREAD

**Issue by kharshita590** [devs-in-tech/DevsInTech#213]
### Description

I WANT TO ADD A FEEDBACK SECTION

**Comment by AbhiPatel10** [comment]
Can you make this type of testimonial ? Have a look on design testimonial section.

https://www.figma.com/proto/XIGflIIAZWQf7tM5UXuOt4/DevsIn-Tech---Open-Source?type=design&node-id=1-474&scaling=scale-down-width&page-id=0%3A1

**Comment by ManasMadan** [comment]
@AbhiPatel10, I can try making the testimonial section as it is in the figma file. But won't be able to animate it, like the cards wont move only the content will change. If you are okay with it please reply don't assign me this right now. Need to ask a few more things.

**Comment by AbhiPatel10** [comment]
If you are able to make a design then well and good animation we can add later on. but design should be responsive and build only using tailwind css

**Comment by kharshita590** [comment]
@AbhiPatel10 I can make that . But i want to know that the testimonials will be submitted by the user and will be shown on testimonials page , something like that

**Comment by AbhiPatel10** [comment]
![image](https://github.com/devs-in-tech/DevsInTech/assets/76242769/ed752abf-ca36-413d-ae4a-9504e5096402)


It will just a static data how it looks on upper image.  @kharshita590 if you can do it then go confirm once and start building.use only tailwind css.

@ManasMadan let @kharshita590 do this.

**Comment by kharshita590** [comment]
Okay @AbhiPatel10 , I will use only tailwind css

**Comment by AbhiPatel10** [comment]
Great go ahead
