### ISSUE TITLE
[BUG] Clicking on Navbar Links Covers Some Part of Section

### ISSUE THREAD

**Issue by ManasMadan** [devs-in-tech/DevsInTech#216]
### Is there any existing issue for this?

- [X] I have searched the existing issues

### Description

 Clicking on Navbar Link scrolls down to that section but cover some part of the section

### Screenshots

<img width="960" alt="image" src="https://github.com/devs-in-tech/DevsInTech/assets/84731321/7819ee34-d75a-457a-8965-542d6b806462">

### What browser are you seeing the problem on?

Chrome

**Comment by ManasMadan** [comment]
@AbhiPatel10 Please assign me this issue under GSSoC 23

**Comment by AbhiPatel10** [comment]
Looks relevant go ahead @ManasMadan

**Comment by ManasMadan** [comment]
@AbhiPatel10 Have created a PR #217, Merging that closes this issue
