### ISSUE TITLE
[Feature] Adding proper content to replace the "Lorem Ipsum..." of the Event Cards [GSSoC'23]

### ISSUE THREAD

**Issue by 1Shubham7** [devs-in-tech/DevsInTech#220]
### Description

The Event cards doesn't have a proper summary or intro. I can add intro for them to make them look more professional and interesting. 

### Screenshots

![cardso](https://github.com/devs-in-tech/DevsInTech/assets/116020663/4b389542-50cb-417f-8549-a7e5457ad95d)
![carsdsoo](https://github.com/devs-in-tech/DevsInTech/assets/116020663/77b13ac5-656f-4ec3-96cf-a2cad96ce3b1)

### Additional Information

Please assign me this issue under GSSoC'23.

**Comment by 1Shubham7** [comment]
Please assign me this issue under GSSoC'23.

**Comment by himanshu1221** [comment]
hey @1Shubham7 this issue will be assigned to the Development team only

**Comment by 1Shubham7** [comment]
Ok @himanshu1221 . I got it.
