### ISSUE TITLE
[Feature] Adding proper answers to the FAOs in the homepage. [GSSoC'23]

### ISSUE THREAD

**Issue by 1Shubham7** [devs-in-tech/DevsInTech#221]
### Description

The FAOs present in the home page don't have appropriate answers. I can add proper answers to those FAQs.

### Screenshots

![faqs](https://github.com/devs-in-tech/DevsInTech/assets/116020663/8a8c3314-6f21-48fc-9931-53376749fc2b)

### Additional Information

Please assign me this issue under GSSoC'23

**Comment by 1Shubham7** [comment]
Please assign me this issue under GSSoC'23.

**Comment by himanshu1221** [comment]
hey @1Shubham7 this issue has already been stated check #136

**Comment by 1Shubham7** [comment]
Ok @himanshu1221 . I got it.
