### ISSUE TITLE
[Enhancement] Adding actual team data to the team page 

### ISSUE THREAD

**Issue by prnvtripathi** [devs-in-tech/DevsInTech#222]
### Description

Right now the team page consists of filler text, I'll work on to change it in actual data.

**Comment by Deepanshu0703** [comment]
Hey @prnvtripathi can you assign this issue to me .

**Comment by prnvtripathi** [comment]
There's already work going on this issue.
Can't assign this to you, please look out for more issues. Thank you 😊
