### ISSUE TITLE
Improve ReadMe.md badges

### ISSUE THREAD

**Issue by VSatwika** [devs-in-tech/DevsInTech#223]
- To improve the look of ReadMe.md badges, I would like to make the necessary changes.
 - I would also like to add more badges.
 - Could this be assigned to me under GSSoC'23?

### Add screenshots

Before 
<img width="532" alt="badge3" src="https://github.com/devs-in-tech/DevsInTech/assets/112561024/87188cb3-0834-46c9-9cfb-f436a73a7e3f">

After 
<img width="625" alt="badges" src="https://github.com/devs-in-tech/DevsInTech/assets/112561024/77fff5c7-973b-4e10-95d2-ef9df44dd587">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by himanshu1221** [comment]
Looks nice!
go ahead @VSatwika assigning you :rocket:

**Comment by Susmita-Dey** [comment]
Closing issue as solved
