### ISSUE TITLE
[BUG] Add Information in the FAQs section[GSSOC'23]

### ISSUE THREAD

**Issue by smty2018** [devs-in-tech/DevsInTech#228]
### Is there any existing issue for this?

- [X] I have searched the existing issues

### Description

 Add Information in the FAQs section and replace the "lorem ipsum" default

### Screenshots

![image](https://github.com/devs-in-tech/DevsInTech/assets/74114936/cd3212fb-a381-469a-8b48-e98a3330930b)

**Comment by smty2018** [comment]
please assign me this issue

**Comment by himanshu1221** [comment]
hey @smty2018 this issue has already been stated #136
