### ISSUE TITLE
[style]:  add better hover effects to social media icons in footer section

### ISSUE THREAD

**Issue by rishuraj1** [devs-in-tech/DevsInTech#231]
### What's the style idea?

- The hover effects on social media icons(facebook, twitter, instagram, discord, linkedin) are plain
- I want to add their original colors to them on hover 

### Add screenshots

before: 

https://github.com/devs-in-tech/DevsInTech/assets/47839626/12c7ca58-d399-4add-b8a8-d21b415c9183

after changes(proposed idea) :

https://github.com/devs-in-tech/DevsInTech/assets/47839626/b601d21f-3dfe-4586-a2a4-e7d76da122a7

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

PS: Please allow me to contribute to this project under GSSoC '23. Thank You!

**Comment by himanshu1221** [comment]
looks good to me go ahead @rishuraj1 assigning you :rocket:
