### ISSUE TITLE
[BUG] Complete the FAQ section with answers to all questions

### ISSUE THREAD

**Issue by poorvijn** [devs-in-tech/DevsInTech#232]
### Is there any existing issue for this?

- [X] I have searched the existing issues

### Description

The FAQ section has a few questions unanswered and is filled with lorem ipsum text. Would like to fill them up!
Could you please assign this issue to me under GSSoC'23?

### What browser are you seeing the problem on?

Chrome

**Comment by himanshu1221** [comment]
hey @poorvijn this issue has already been assigned #136
