### ISSUE TITLE
[Feature] <description> Add a moving effect in Testimonial section.

### ISSUE THREAD

**Issue by bhavyasingh75** [devs-in-tech/DevsInTech#233]
### Description

The testimonial section has an individual hover card for each member. It would be nice if it has a smooth transition which would make the website more interactive.

**Comment by himanshu1221** [comment]
Looks relevant to me go ahead assigning you @bhavyasingh75 :rocket:

**Comment by abhinav-m22** [comment]
@himanshu1221 @Susmita-Dey 
Can I work on this issue as it is inactive?
Please assign me!
