### ISSUE TITLE
[style]: The background of the website is plane, Adding a gradient to it.

### ISSUE THREAD

**Issue by 1Shubham7** [devs-in-tech/DevsInTech#234]
### What's the style idea?

We need to improve  upon the background for the website. By replacing the plane background with a gradient.

### Add screenshots

Here are some sample gradients, I can create more if the you want more:
![GRADIENTS](https://github.com/devs-in-tech/DevsInTech/assets/116020663/cbdf8423-9448-4a0a-81e4-dbd657b5129c)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 1Shubham7** [comment]
Please assign me this issue under GSSoC'23.

**Comment by himanshu1221** [comment]
hey @AbhiPatel10 check this out

**Comment by Susmita-Dey** [comment]
Hey @1Shubham7 Try using the blue gradient and show us once. We'll choose.

**Comment by Abhinavcode13** [comment]
please assign this issue to me now @Susmita-Dey

**Comment by 1Shubham7** [comment]
@Susmita-Dey Unable to find how to add gradient in this project, there is no proper css files. Please help !

**Comment by Susmita-Dey** [comment]
It's using tailwind css
