### ISSUE TITLE
[BUG] Improve navigation to sections 

### ISSUE THREAD

**Issue by suryanshsoni120** [devs-in-tech/DevsInTech#239]
### Is there any existing issue for this?

- [X] I have searched the existing issues

### Description

On selecting the events or team tab from the navbar, the page loaded is incorrect. Need to update the path. Please assign me this issue under GSSOC'23.

### Screenshots

![image](https://github.com/devs-in-tech/DevsInTech/assets/63662732/e8e54f16-d756-455b-acc3-13034efdd22a)
Correct page

![image](https://github.com/devs-in-tech/DevsInTech/assets/63662732/882e4306-6391-4698-9d89-df5b807240eb)
Incorrect page

**Comment by oshinsaraf** [comment]
I could add the transitions required to navigate to the next page, please assign this issue to me under GSSOC'23.

**Comment by suryanshsoni120** [comment]
@Susmita-Dey , shall i include the team section on the home page?

**Comment by Susmita-Dey** [comment]
@suryanshsoni120 Not needed

**Comment by Abhinavcode13** [comment]
can i work on this @Susmita-Dey
