### ISSUE TITLE
[Docs]: Enhance the README 

### ISSUE THREAD

**Issue by MisterMickey** [devs-in-tech/DevsInTech#241]
### what's wrong in the documentation?

I need to enhance the README to make it free of grammatical errors and easy to understand with a more appealing view.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shrey-a-gupta** [comment]
Hi @MisterMickey , I am willing to work on this issue. May I ?

**Comment by shrey-a-gupta** [comment]
Is this issue under GSSoC'23 ?

**Comment by MisterMickey** [comment]
@shrey-a-gupta I have raised it under GSSOC only but make sure that when you raise your PR it must have label of gssoc23.

**Comment by MamathaKarapanahalli** [comment]
Can I take this up?

**Comment by Susmita-Dey** [comment]
Assignedit to @shrey-a-gupta since @MisterMickey gave up to her!
