### ISSUE TITLE
[style]: Adding hover effect in the navbar.

### ISSUE THREAD

**Issue by 1Shubham7** [devs-in-tech/DevsInTech#242]
### What's the style idea?

We need to improve  :
The navbar of the website can be significantly improved by adding a hover effect. 

### Add screenshots

Add screenshots :
Nothing to add here

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 1Shubham7** [comment]
Please assign me this issue.

**Comment by Susmita-Dey** [comment]
Duplicate issue check #227
