### ISSUE TITLE
[OTHER] Add the Team member names and update their social media handles [GSSOC'23]

### ISSUE THREAD

**Issue by Ujwal19k** [devs-in-tech/DevsInTech#244]
### What would you like to share or ask?

The "Team" page has only one picture and its social media handle. I request you to assign me this issue where I will add the team member names and their handles.  [GSSOC'23]

**Comment by Susmita-Dey** [comment]
Hey, you need data for that. @devs-in-tech/devsintech-web-team Someone kindly push the data to the repository

**Comment by prnvtripathi** [comment]
@Susmita-Dey I already created an issue related to this, and I've updated all the information, just going to make the PR today only.

**Comment by Susmita-Dey** [comment]
Hey @Ujwal19k This is a duplicate issue. You can't work on this
