### ISSUE TITLE
[Feature] <Change the "What Our Members Say About Us" section card ui>

### ISSUE THREAD

**Issue by SubhamB2003** [devs-in-tech/DevsInTech#245]
### Description

Hey, I want to improve the "What Our Members Say About Us" card UI.

Previously

![image](https://github.com/devs-in-tech/DevsInTech/assets/94003231/c6f967c9-5819-4e2a-8ff7-eceacc0c38a8)

After made changes

![image](https://github.com/devs-in-tech/DevsInTech/assets/94003231/bba92bea-e12b-481a-a215-0fdc644ff71b)

Please assign it to me under the GSSOC'23.

**Comment by Susmita-Dey** [comment]
@SubhamB2003 This seems to be the output of `build` command in Next.js

**Comment by Susmita-Dey** [comment]
First pull the recent changes and then push

**Comment by SubhamB2003** [comment]
> First pull the recent changes and then push

Yeah, it's solved. You can check now
