### ISSUE TITLE
[Docs]: Addition of dependabot.yml file

### ISSUE THREAD

**Issue by Anshika-Jain02** [devs-in-tech/DevsInTech#247]
### what's wrong in the documentation?

*We need to add dependabot.yml file as it helps us to keep our dependencies up to date. Every day, it checks your dependency files for outdated requirements and opens individual PRs for any it finds.*

**@Susmita-Dey please assign me this issue under gssoc'23.**

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Abhinavcode13** [comment]
assign this issue to me @Susmita-Dey @prnvtripathi now please !

**Comment by Susmita-Dey** [comment]
Hey @Abhinavcode13 PR is already made. You may find some other issues or create a new one
