### ISSUE TITLE
[style]: Typewriter effect in Heading

### ISSUE THREAD

**Issue by Anshika-Jain02** [devs-in-tech/DevsInTech#248]
### What's the style idea?

*We can add a typewriter effect in the below heading to give a dynamic effect and to improve the visual appearance of the overall website.*

![devstech](https://github.com/devs-in-tech/DevsInTech/assets/104912087/bd8b6fe3-3af6-4227-a70e-f2bb49777fcb)

**@Susmita-Dey Please assign me this issue under gssoc'23**

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Susmita-Dey** [comment]
Hey @Anshika-Jain02 Some issues have also been assigned to you. Kindly complete them first and then ping me here again

**Comment by rishuraj1** [comment]
hey @Susmita-Dey  Could you let me work on this one please.

**Comment by Susmita-Dey** [comment]
Hey @rishuraj1 It's first-come first-serve basis. So, if @Anshika-Jain02 gives up,then I might assign it to you
