### ISSUE TITLE
[Feature] Create a contributors page

### ISSUE THREAD

**Issue by karthiknadar1204** [devs-in-tech/DevsInTech#250]
### Description

Proposed solution:
Implement a contributors page which will be routed on the navbar, this page shall have the avatar of all the contributors in the form of cards along with links which shall redirect the user to their github accounts.

The avatar and the link will be beautifully aligned in different cards.The contributors will be placed in descending order of the pr's made to the project.

**Comment by karthiknadar1204** [comment]
I would like to work on this issue under gssoc'23

**Comment by karthiknadar1204** [comment]
Thank you so much @Susmita-Dey , will get to working on it

**Comment by karthiknadar1204** [comment]
@Susmita-Dey Will start work on this issue after 1st july.
Thank you

**Comment by karthiknadar1204** [comment]
Just a heads up, have begun the work, API is generating contributors data perfectly, just having some issues with the routing of data.
Is the project not using router @Susmita-Dey ,  The links have been mapped but I did not notice any routers.

**Comment by Susmita-Dey** [comment]
Hey @karthiknadar1204 React-router is not needed as this is a Next.js project.

@devs-in-tech/devsintech-web-team Can someone assist him?

**Comment by karthiknadar1204** [comment]
Will be working out the navigation problem again from 1:45 today,will share if any issue occurs

**Comment by prnvtripathi** [comment]
@karthiknadar1204 Reach out to the @devs-in-tech/devsintech-web-team team any time, we'll be happy to help. Or ping us in Discord server.

**Comment by karthiknadar1204** [comment]
Thank you @prnvtripathi

**Comment by karthiknadar1204** [comment]
Have fixed the routing issue, able to map the data from the API perfectly on the page, only styling is left now @Susmita-Dey

**Comment by karthiknadar1204** [comment]
Is it fine if i use a separate CSS file for the styling, offers more freedom in styling the individual elements classwise

**Comment by karthiknadar1204** [comment]
@Susmita-Dey Have finished the entire page, have also made it responsive, submitting pr for review in a bit
