### ISSUE TITLE
[Feature]  Adding a booking feature for events.

### ISSUE THREAD

**Issue by nupurthikekar** [devs-in-tech/DevsInTech#251]
### Description

Hey, I saw the project and I liked the UI but I feel the backend is missing. Most of the site is static and I saw that there are a lot of good events for developers on the site. But how about we make a booking feature for the events. As I see that we are hosting workshops and webinars so it will be helpful for the web app to build a booking feature for events. How I think about this feature is that we can store the user's data that clicked on the book slot button and send a pdf to their mail or after clicking the button a pdf automatically downloads and information about the event is displayed in that pdf and the user's name or just show a modal that your registration for the event has been done.

**Comment by Susmita-Dey** [comment]
Hey, this is a great idea. Let me know how you wanna implement it.

**Comment by Nishitbaria** [comment]
> Hey, this is a great idea. Let me know how you wanna implement it.

hey @Susmita-Dey  I can able to implement this feature assign me this issue

**Comment by Susmita-Dey** [comment]
> > Hey, this is a great idea. Let me know how you wanna implement it.
> 
> hey @Susmita-Dey  I can able to implement this feature assign me this issue 

How do you want to do it? By using sendgrid or something else?

**Comment by Nishitbaria** [comment]
@Susmita-Dey ,I will do it using nodemailer and gmail  as a smtp service and if you want i can use any other smtp service like mailchimp,mailgun

**Comment by Susmita-Dey** [comment]
Hey @Nishitbaria This sounds amazing. Assigning it to you as @nupurthikekar didn't show up for long time

**Comment by Nishitbaria** [comment]
@Susmita-Dey,please explain your requirement for this booking feature

**Comment by Susmita-Dey** [comment]
Something similar to WMD events
