### ISSUE TITLE
[BUG]  The contributors list in the Readme is not visible

### ISSUE THREAD

**Issue by abhi03ruchi** [devs-in-tech/DevsInTech#252]
### Is there any existing issue for this?

- [X] I have searched the existing issues

### Description

 

I would like to add the correct URL of the contributor's list in the Readme. Correcting this section of readme would enhance the readme. 

### Screenshots

<img width="644" alt="Screenshot 2023-06-16 at 9 28 59 PM" src="https://github.com/devs-in-tech/DevsInTech/assets/105661636/59f99ce9-69df-4f46-9166-ba34c7382fac">

### Any additional information?

Plz assign me this issue under gssoc'23.

### What browser are you seeing the problem on?

Chrome, Safari

**Comment by Susmita-Dey** [comment]
Hey @abhi03ruchi Seems like there's no such bug now. Closing this as already done
