### ISSUE TITLE
[Feature] Hover effect is missing in the team section icons

### ISSUE THREAD

**Issue by HimanshuNarware** [devs-in-tech/DevsInTech#253]
### Description

I want to add a hover effect on the Team section icons  and team member profile section, I want to work on this issue.

### Screenshots

![8](https://github.com/devs-in-tech/DevsInTech/assets/83147410/534fcaa1-d14e-4857-8353-fc989d741db9)

**Comment by prnvtripathi** [comment]
The team is already working on the issue, thank you.
