### ISSUE TITLE
[style]: Event section need UI improvement.

### ISSUE THREAD

**Issue by HimanshuNarware** [devs-in-tech/DevsInTech#254]
### What's the style idea?

We need to improve the Event section on the website, The box in the website need improvement 

### Add screenshots

Add screenshots
![9](https://github.com/devs-in-tech/DevsInTech/assets/83147410/2d0204ec-8763-44b5-b2ab-76cc99a5aae1)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by prnvtripathi** [comment]
How do you plan on improving the UI?

**Comment by HimanshuNarware** [comment]
My plan is to improve the UI of the boxes present in the event section the box background does not match the theme of the website, and I want to give a decent design to the box also the width and height of the content box are not effective, I want to give decent look to the event section
