### ISSUE TITLE
ADD DARK AND LIGHT MODE FEATURE

### ISSUE THREAD

**Issue by raghav1482** [devs-in-tech/DevsInTech#255]
### Description

I want to add Dark and Light mode feature to this project to make it look more appealing and attractive.

**Comment by raghav1482** [comment]
@prnvtripathi kindly assign me this issue(#255) under GSSOC 2023

**Comment by prnvtripathi** [comment]
@raghav1482 This feature isn't planned. So, closing this issue.
Please look out for any other issues.
