### ISSUE TITLE
[Feature] Hover effect on card and animation

### ISSUE THREAD

**Issue by Niladri2003** [devs-in-tech/DevsInTech#256]
### Description

I want to add some hover effect in Latest events in devsintech sections cards and add some animations

**Comment by Abhinavcode13** [comment]
Can i work on this issue if no response from the contributor please assign me @Susmita-Dey @prnvtripathi

**Comment by Susmita-Dey** [comment]
Hey @Abhinavcode13 
@Niladri2003 is already working on the issue.
