### ISSUE TITLE
[Feature] Adding Preloading Screen

### ISSUE THREAD

**Issue by SubhamB2003** [devs-in-tech/DevsInTech#259]
### Description

Hey, I want to add the preloading screen before the website is loaded.

Can you please assign it to me under the GSSOC'23 ?

Here is a demo
https://github.com/DevFeed404/DevFeed-1.0/assets/94003231/991056fa-90cf-40e5-9e99-692cf4547053

**Comment by Susmita-Dey** [comment]
Duplicate issue #133
