### ISSUE TITLE
Adding a pre loader to the website 

### ISSUE THREAD

**Issue by Illaf** [devs-in-tech/DevsInTech#261]
### Description

The website loads in a few milliseconds. While the website is loading , a pre loader can be added to the website. 

### Additional Information

If you want I can also add a HTML CSS javascript loader

**Comment by Illaf** [comment]
I am a gssoc'23 contributor

**Comment by Susmita-Dey** [comment]
Hey @Illaf This website is built with Next.js and React.js so normal html js won't work. Files mostly have .jsx extension

**Comment by Susmita-Dey** [comment]
Let me know if you can do it and also what type of preloader you have thought to add?

**Comment by Susmita-Dey** [comment]
Also, this seems a duplicate issue like #133 #259
