### ISSUE TITLE
[Feature] Dockerize the application

### ISSUE THREAD

**Issue by abhinav-m22** [devs-in-tech/DevsInTech#263]
### Description

I want to containerize the application by creating a Dockerfile and a corresponding dockerignore file.

Dockerizing the application will enable us to package it along with its dependencies into a container, ensuring consistent and reliable deployments across different environments. 
By using Docker, we can easily spin up and scale multiple instances of the application, making it more robust and efficient. 

This issue aims to implement Dockerization for the application, streamlining our deployment workflow and enhancing its overall performance and portability.

### Additional Information

I want to work on this issue.
Please assign me the task under GSSoC'23.

**Comment by abhinav-m22** [comment]
@himanshu1221 @Susmita-Dey Please assign me the issue

**Comment by abhinav2712** [comment]
@himanshu1221 @Susmita-Dey I am quite active in devops and can even solve this issue with extra steps lik implementing CI/CD as well, assign me this issue

**Comment by Susmita-Dey** [comment]
Hey @abhinav2712 Go ahead!
