### ISSUE TITLE
[style]: Improve UI of the What our Member says about us section.

### ISSUE THREAD

**Issue by Pragati-3003** [devs-in-tech/DevsInTech#265]
### What's the style idea?

I would like to improve the ui of  What our Member says about us section to make it more attractive by adding some cool effects and also by adjusting the existing css.
So,please assign this issue to me under gssoc'23.

### Add screenshots

![Screenshot 2023-06-24 015355](https://github.com/devs-in-tech/DevsInTech/assets/132778037/2fe25878-3249-4698-b501-436e683dc4b7)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by prnvtripathi** [comment]
How do you plan on improving the UI?

**Comment by Pragati-3003** [comment]
> How do you plan on improving the UI?

I would like  to add some hover effects and box-shadows also would like to adjust the css like margin, padding, etc.
