### ISSUE TITLE
[Feature]  Hover effect issue in navbar

### ISSUE THREAD

**Issue by HimanshuNarware** [devs-in-tech/DevsInTech#266]
### Description

The hover effect present in the navbar content is unattractive, I want to improve the hover effect on the navbar content, and I want to add animation in which the line goes left to right when some hover over it

### Screenshots

![68](https://github.com/devs-in-tech/DevsInTech/assets/83147410/02307c72-6195-43ca-a343-28c9c36d55fe)

**Comment by rohittiwari-dev** [comment]
hey I would like to work on [Feat] #266, if you assign me #266
