### ISSUE TITLE
[Feature] Redesign the Events page

### ISSUE THREAD

**Issue by abhinav-m22** [devs-in-tech/DevsInTech#271]
### Description

Currently the **Events** page has only event cards similar to the home page.

I would like to enhance it by following ways:
1. Add an introduction to the events page.
2. Add some plus points about the DevsinTech community.
3. Advantages of attending the events like "Why attend devsintech events?"
4. Add links to these events(even if completed)

### Screenshots

<img width="960" alt="image" src="https://github.com/devs-in-tech/DevsInTech/assets/113239388/a9bd31b2-3659-40df-96d8-913e587f0122">

### Additional Information

Please assign me the issue under gssoc

**Comment by Susmita-Dey** [comment]
Hey @abhinav-m22 Don't you think that a separate event page would be better for that listing out different types of events and then subpages listing out different events for that particular event category with past and upcoming sections?

Also, someone is working on events issue so you need to wait for them to make PR for atleast a week

**Comment by abhinav-m22** [comment]
@Susmita-Dey That's what I am saying ma'am
When we click the Events section from the navbar, the page is redirected to a new route '/events' which is a new page.
And that new page should be designed in a way as you have mentioned

**Comment by Susmita-Dey** [comment]
Okay, got it. I was thinking about the home page. Anyways, go ahead. 


Note: Apart from workshop and webinars we do quiz nights, coffee chat, twitter space, blog-a-thon, movie night and meme-a-thon. 

So, you may create cards based on categories of your choice and then subpages for each one.

**Comment by abhinav-m22** [comment]
Yeah sure.. Thanks!

**Comment by Susmita-Dey** [comment]
For inspiration, you may check:- https://wemakedevs.org/events/
