### ISSUE TITLE
Logo does not navigate to the homepage

### ISSUE THREAD

**Issue by crocmons** [devs-in-tech/DevsInTech#272]
### Is there any existing issue for this?

- [X] I have searched the existing issues

### Description

The logo is not clickable & also does not navigate to the homepage...I want to fix this issue so that users can easily click the logo & redirect to the homepage..Kindly Assign this issue to me as a GSSOC23 contributor

[screencast-www.linkedin.com-2023.06.28-14_26_17.webm](https://github.com/devs-in-tech/DevsInTech/assets/106610322/9b96fd7e-b1cf-45b8-a015-a1c12b1a1859)

**Comment by Susmita-Dey** [comment]
@crocmons I don't think that you have really searched if the same issue has already been created or not. This is a duplicate issue due to #243 

Kindly check next time before making duplicate issues. Happy Open Sourcing! 🙂
