### ISSUE TITLE
[BUG]  Add Relevant Testimonials to "What Our Members Say About Us" Section and Add  Testimonial Collection Form:

### ISSUE THREAD

**Issue by Nishitbaria** [devs-in-tech/DevsInTech#273]
### Is there any existing issue for this?

- [X] I have searched the existing issues

### Description

- Currently, the "What Our Members Say About Us" section displays generic placeholder text that does not provide any meaningful information to visitors.
- Adding authentic testimonials will significantly enhance the credibility and trustworthiness of our website and services.
- Genuine testimonials will help potential users gain insights into the experiences of our existing members and make informed decisions about joining our platform.
- Testimonials should include the name, occupation, and optionally a profile picture of the member to add a personal touch.
- We should prioritize testimonials that highlight specific benefits or success stories related to our platform, such as career advancements, skill development, networking opportunities, or positive impact on their professional lives.
- It is essential to regularly update the testimonials to keep the section fresh and relevant.

## Action Steps
1. Add Relevant Testimonials: Gather testimonials from our existing members who have expressed satisfaction with our services. Request permission to feature their testimonials on the website. Ensure testimonials showcase diverse positive experiences and benefits our platform offers.
2. Implement Testimonial Collection Form: Create a dedicated form on the website where users can submit their testimonials. The form should include fields for their name, occupation, testimonial content, and an option to upload a profile picture.

### Screenshots

![image](https://github.com/devs-in-tech/DevsInTech/assets/85815172/56627d21-5fc8-4e21-8a91-24dda5db064a)

### Any additional information?

I am ready to work on your feedback ,you can assign me this issue.

### What browser are you seeing the problem on?

Microsoft Edge

**Comment by Nishitbaria** [comment]
@Susmita-Dey Which photos should I use for testimonials

**Comment by Nishitbaria** [comment]
> Add dummy photos as of now

I  have  created PR please Review it

**Comment by Susmita-Dey** [comment]
@Nishitbaria Link the issue number in your PR

**Comment by Susmita-Dey** [comment]
Hey @Nishitbaria Can you push it again?

Seems like for some reason there some issue and it's removed from the website

**Comment by Nishitbaria** [comment]
@Susmita-Dey ,Should i make a new pull request?

**Comment by Susmita-Dey** [comment]
Hey @Nishitbaria Create a new issue first with the bug and it seems like import is not done properly for the testimonial component. I'll assign you. Closing this now.

**Comment by Nishitbaria** [comment]
@Susmita-Dey I have made new issue #326,please check
