### ISSUE TITLE
[style]: Hover effect on social icons on the navbar

### ISSUE THREAD

**Issue by karthiknadar1204** [devs-in-tech/DevsInTech#278]
### What's the style idea?

I was thinking of adding hover effect to the social icons on navbar such that on hovering the colour of the icons turn to their standard colours like purple for discord, black for github, light blue for twitter and blue for LinkedIn.
I think that would add a charm to the navbar.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by karthiknadar1204** [comment]
I would like to work on this issue under gssoc'23

**Comment by karthiknadar1204** [comment]
@Susmita-Dey Right now the codebase is using svg icons for the social media icons, so the new colours are getting added to the background, is it fine if I used react icons , that we we could fill the colour into the icon instead of the background

**Comment by Susmita-Dey** [comment]
@karthiknadar1204 Yes, it would be better to use react-icons

**Comment by karthiknadar1204** [comment]
I tried installing but unable to do it in a next-js project showing error

**Comment by karthiknadar1204** [comment]
Went with adding hover effect to the SVG icons only, should work as a temporary measure
