### ISSUE TITLE
[BUG]: Improve Font Weight much Better in Footer Top Right Section

### ISSUE THREAD

**Issue by NarendraKoya999** [devs-in-tech/DevsInTech#285]
### Is there any existing issue for this?

- [X] I have searched the existing issues

### Issue Description
- **Improve Font Weight Much Better in Footer Top Right Section**

### Screenshots

![devsintech-1](https://github.com/devs-in-tech/DevsInTech/assets/84512164/125194e9-d152-4281-9039-8045b670e571)

### What browser are you seeing the problem on?

Chrome

**Comment by Susmita-Dey** [comment]
Hey @NarendraKoya999 You need to wait as someone is already working on the right side text of the footer. Kindly work on the already assigned task.

**Comment by NarendraKoya999** [comment]
Ok. Sure @Susmita-Dey

**Comment by NarendraKoya999** [comment]
**Hi @Susmita-Dey . It's Already Merged. Please Closed This PR and related Issue as soon as possible**

**Comment by NarendraKoya999** [comment]
Thank You @Susmita-Dey
