### ISSUE TITLE
[style]: Make the navbar translucent

### ISSUE THREAD

**Issue by karthiknadar1204** [devs-in-tech/DevsInTech#290]
### What's the style idea?

In the current navbar, When scrolling down the opaque black navbar looks bleak, instead we can make the navbar translucent i.e reduce the overall opacity of the navbar so that when the sticky navbar scrolls down, instead of all black, we can make it look partly transparent/translucent.

This would make the navbar look more attractive in the longer run.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by karthiknadar1204** [comment]
I would like to work on this issue under gssoc'23

**Comment by karthiknadar1204** [comment]
https://github.com/devs-in-tech/DevsInTech/assets/95973644/a165c4de-4876-48df-a136-153aeedcada7


@Susmita-Dey What do you think of the navbar in the preview, was thinking of using it in this project as well.
Your opinion

**Comment by Susmita-Dey** [comment]
@devs-in-tech/devsintech-web-team What do you think about it?

**Comment by karthiknadar1204** [comment]
@Susmita-Dey Any update on this issue?

**Comment by Susmita-Dey** [comment]
Not sure if it would look good or not

**Comment by karthiknadar1204** [comment]
Can I give it a try @Susmita-Dey , will share a preview here before submitting the pr for review, is that fine?

**Comment by Susmita-Dey** [comment]
Go ahead

**Comment by karthiknadar1204** [comment]
https://www.awesomescreenshot.com/video/18938102?key=65cb7172996388e313eca2fc45162549



@Susmita-Dey What do you think, should i submit pr for review?

**Comment by karantec** [comment]
please assign me this issue i will solve under GSSOC'23

**Comment by prnvtripathi** [comment]
Go ahead, make the PR, thanks for contributing.

**Comment by prnvtripathi** [comment]
@Susmita-Dey , i think the navbar looks cool with this translucent nature, what do you think?

**Comment by karthiknadar1204** [comment]
Will make the pr in a bit,thank you

**Comment by karthiknadar1204** [comment]
Done @prnvtripathi 
Thank you
