### ISSUE TITLE
[Feature] Add Preloader Animation

### ISSUE THREAD

**Issue by smty2018** [devs-in-tech/DevsInTech#294]
### Description

Currently , while loading the page, it show white blank page. Want to add a preloading(loader for a website before content is loaded in the browser) animation to enhance style.

https://github.com/devs-in-tech/DevsInTech/assets/74114936/1150a077-a589-4354-8bed-f2120e9c3b23

want to add something like any of  these
![nQQMcLY](https://github.com/devs-in-tech/DevsInTech/assets/74114936/b09cf858-067c-4f72-b7d1-1a0cea2ae4cf)

**Comment by Susmita-Dey** [comment]
Duplicate issue #133
