### ISSUE TITLE
adding animation effects to the entire website

### ISSUE THREAD

**Issue by Illaf** [devs-in-tech/DevsInTech#295]
### Description

The idea is to add animation effects such as fade-in , up ,left right and many more to the texts,divs and images of the website.
This will definitely make the website look more dynamic, attractive and user friendly. Animations always throw a good and impressive outlook to the user. I would strongly suggest adding animations to this beautiful website

**Comment by Susmita-Dey** [comment]
Hey @Illaf Do you wanna use any external library for this or framer-motion?

**Comment by Susmita-Dey** [comment]
Putting this issue on hold as of now
