### ISSUE TITLE
Redesigning the footer section

### ISSUE THREAD

**Issue by Illaf** [devs-in-tech/DevsInTech#296]
### Description

The footer is almost merged with the main content and the links are also not properly visible due to pitch black colour of the website. Hence it is important to add some UI to the footer.

### Screenshots

Please have a look
![2023-06-29 (2)](https://github.com/devs-in-tech/DevsInTech/assets/114517448/d79737d9-3dda-4b2d-860a-6c8a5d8a6251)

**Comment by Susmita-Dey** [comment]
It's kinda updated now. Also, there still some scope to improve it and make it better. Let me what are your thoughts on it and do have any design inspiration in your mind or not.

**Comment by Illaf** [comment]
@Susmita-Dey yes as you can see the links under community and events section are not visible. I can improve it
![Screenshot (20)](https://github.com/devs-in-tech/DevsInTech/assets/114517448/290d2a8e-c551-410f-8e93-4aa360906bbb)

**Comment by Susmita-Dey** [comment]
First do git pull to see the new changes on localhost.

**Comment by Illaf** [comment]
But this footer also shows up at the website of DivsIntech @Susmita-Dey 
![Screenshot (21)](https://github.com/devs-in-tech/DevsInTech/assets/114517448/085a2cd8-11a5-4704-a493-818c60fe2e41)

**Comment by Susmita-Dey** [comment]
![image](https://github.com/devs-in-tech/DevsInTech/assets/79099734/b4498419-1dee-40b5-b2be-46661890d37e)
It looks different in my case

**Comment by karantec** [comment]
please assign me this issue i will solve under GSSOC'23
