### ISSUE TITLE
[style]: Add hover to social icons on footer

### ISSUE THREAD

**Issue by karthiknadar1204** [devs-in-tech/DevsInTech#298]
### What's the style idea?

Add similar hover effect to the social icons on the footer like we have on. the navbar, it would look more elegant.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by karthiknadar1204** [comment]
I would like to work on this issue under gssoc'23

**Comment by karthiknadar1204** [comment]
@Susmita-Dey Can i work it out?

**Comment by Susmita-Dey** [comment]
Footer is gonna change so it won't be useful to work on.
