### ISSUE TITLE
[Feature] Develop a Webinars page

### ISSUE THREAD

**Issue by abhinav-m22** [devs-in-tech/DevsInTech#299]
### Description

Currently, there is an option for **Webinars** in the footer section, but there does not exist any page for it.
I would like to design and develop the required page with the necessary content.
There could be cards showing the details for the required event and when the cards are click, we could show a dialog box which would provide links and more description about the webinar.

I had designed the events page for the website recently...

### Screenshots

<img width="950" alt="image" src="https://github.com/devs-in-tech/DevsInTech/assets/113239388/d9c2c3ac-55f6-45ef-bf8e-0548fffa06f8">

### Additional Information

Please assign me the issue and do let me know your suggestions .

**Comment by Susmita-Dey** [comment]
![image](https://github.com/devs-in-tech/DevsInTech/assets/79099734/671ae5e4-8593-4d89-9aef-b370bef55ee0)

Hey @abhinav-m22 It was dummy. Also, what you can do is rename "Online Tech Events" to Webinar.

**Comment by Susmita-Dey** [comment]
Shall I assign it to you?

**Comment by abhinav-m22** [comment]
> Shall I assign it to you?

Yes
I will work on it and do the required
