### ISSUE TITLE
[Feature] Redesign the numbers section in About section

### ISSUE THREAD

**Issue by abhinav-m22** [devs-in-tech/DevsInTech#300]
### Description

Currently the numbers/statistics section in the about section does not look good. It looks more as a static component.
I would like to redesign the component to somewhat like shown below.

Responsive cards would be added along with animations and hover effects which would improve the UI and UX of the page.

### Screenshots

Currently:
<img width="916" alt="image" src="https://github.com/devs-in-tech/DevsInTech/assets/113239388/34a1e509-1f62-4437-a51d-69d0d8ff7d5a">

Proposed:
<img width="958" alt="image" src="https://github.com/devs-in-tech/DevsInTech/assets/113239388/f9d58c06-978f-41f6-b57d-0898d84beeb7">

### Additional Information

Please assign me the issue under GSSoC23.

**Comment by Susmita-Dey** [comment]
Hey @abhinav-m22 Don't copy the same design as you have proposed otherwise it would be kinda copyright. I'm part of WeMakeDevs core team and I can't allow this copy paste thing for my own community. I hope you understand.

**Comment by Susmita-Dey** [comment]
Assigning this to you to enhance the section. You may find design inspirations from Dribbble or Behance.

**Comment by abhinav-m22** [comment]
> Hey @abhinav-m22 Don't copy the same design as you have proposed otherwise it would be kinda copyright. I'm part of WeMakeDevs core team and I can't allow this copy paste thing for my own community. I hope you understand.

Yes ma'am I would not copy same design. It's just as an example. I would implement custom stylings of my own and share the screenshots first... And then only it would be reviewed.
