### ISSUE TITLE
[Feature] Adding the option to change from dark to light mode and vice versa

### ISSUE THREAD

**Issue by varshanim** [devs-in-tech/DevsInTech#304]
### Description

I would like to add an option on the Navbar that would help the user toggle between light mode and dark mode. It would display the image of a sun to toggle into light mode and when in dark mode it will display the image of the moon to toggle back into dark mode.

### Screenshots

![Screenshot 2023-07-01 at 1 15 28 AM](https://github.com/devs-in-tech/DevsInTech/assets/105119278/0a4782b4-a402-4180-a704-1ffd6dec715d)

## Proposed Idea:

![Screenshot 2023-07-01 at 1 16 56 AM](https://github.com/devs-in-tech/DevsInTech/assets/105119278/b2cc7e79-f606-4864-aafd-bafe78c0e990)

![Screenshot 2023-07-01 at 1 17 06 AM](https://github.com/devs-in-tech/DevsInTech/assets/105119278/bdd811d6-bbbd-4e81-9330-752928f910b3)

### Please assign this issue to me under GSSoC'23.

**Comment by varshanim** [comment]
Hey @Susmita-Dey I've been trying to look for the main `.html` file to make some changes in and add the images in but i cant find it. Can you please provide me with the link of the `.html` file for this webiste?

**Comment by KrunalGupta02** [comment]
Can i work on it under gssoc label.
