### ISSUE TITLE
[Feature] <changing the font of events page>

### ISSUE THREAD

**Issue by Illaf** [devs-in-tech/DevsInTech#306]
### Description

The font of the events page can be improved so that it looks more decent and elegant

### Screenshots

![Screenshot (23)](https://github.com/devs-in-tech/DevsInTech/assets/114517448/78fb496b-2e86-484d-a5e2-50a23c2f9e32)

**Comment by Shatakshi0** [comment]
I would like to work on this issue under gssoc'23

**Comment by prnvtripathi** [comment]
> I would like to work on this issue under gssoc'23

This issue is already been fixed, @Shatakshi0 Please look out for any other issue. Happy Contributing.
