### ISSUE TITLE
[Feature] Develop a custom 404/Not Found Page for non-existing routes

### ISSUE THREAD

**Issue by abhinav-m22** [devs-in-tech/DevsInTech#312]
### Description

As a developer, I would like to create a custom 404 (not found) page to handle undefined or not-existing routes on the website. Currently, when users encounter a non-existent page or route, they are presented with a default error page that lacks user-friendly information.

To enhance the user experience and provide clear feedback, I propose developing a custom 404 page that gracefully handles such situations.

This improvement will contribute to overall user satisfaction and reduce frustration associated with dead-end pages.

### Screenshots

Current Error Page:
<img width="892" alt="image" src="https://github.com/devs-in-tech/DevsInTech/assets/113239388/e5f90eea-bbd8-4ad7-b7ec-b39608c53fce">

### Additional Information

Please assign me the issue under GSSoC23.

**Comment by prnvtripathi** [comment]
Go ahead, assigning the issue to you. @abhinav-m22
