### ISSUE TITLE
[style]: Enhance the ui of teams page

### ISSUE THREAD

**Issue by karthiknadar1204** [devs-in-tech/DevsInTech#313]
### What's the style idea?

The teams page currently has static data spread out, I was thinking of having them placed into distinctly visible cards along with some hover effects to the cards, slightly enlarge the social icons on the page and add hover effects to them a well and further more changes to make the cards look attractive to a new user.

Will share a preview while making the pr, if you have any other styling to be applied, please share it as well, will do

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by karthiknadar1204** [comment]
I would like to work on this issue under gssoc'23

**Comment by karthiknadar1204** [comment]
@prnvtripathi @Susmita-Dey Can i work it out

**Comment by Susmita-Dey** [comment]
Hey @karthiknadar1204 You need to wait for that as @prnvtripathi is already working on it

**Comment by karthiknadar1204** [comment]
Ok works, will wait
Thank you
Could you please suggest any other issue you would like to get done, would love to contribute more to the project @Susmita-Dey

**Comment by Susmita-Dey** [comment]
@karthiknadar1204 Create a new issue to search typos in the website and fix them. probably there are typos for "DevsInTech". Not written properly some are in small case and what not

**Comment by karthiknadar1204** [comment]
Will check them and raise an issue soon
