### ISSUE TITLE
[Feature]  Meetups addition

### ISSUE THREAD

**Issue by Abhinavcode13** [devs-in-tech/DevsInTech#314]
### Description

Adding meetups card in the event section as it is equally important to know the community people in person and having smooth sharing of ideas between them.

**Comment by Abhinavcode13** [comment]
please assign this issue to me @prnvtripathi & @Susmita-Dey

**Comment by Susmita-Dey** [comment]
@Abhinavcode13 We haven't organized any meetups yet and plan to do so is too far. Closing this issue as not needed right now
