### ISSUE TITLE
[Feature] Add hover and good animation to cards

### ISSUE THREAD

**Issue by Abhinavcode13** [devs-in-tech/DevsInTech#315]
### Description

Hover effects can provide visual feedback to users, indicating that the card is interactive and can be clicked or selected. This helps improve the user interface's intuitiveness and provides a clear indication of interactive elements.

**Comment by Abhinavcode13** [comment]
Please assign me this issue @Susmita-Dey @prnvtripathi

**Comment by KmKalpana** [comment]
I would like to work on this issue could you please assign me this issue.

**Comment by Susmita-Dey** [comment]
Hey @Abhinavcode13 Can you share the screenshot of which area you're talking about?

**Comment by prnvtripathi** [comment]
@KmKalpana Please look out for any other issue, as @Abhinavcode13 will most likely work on it.

**Comment by Abhinavcode13** [comment]
![Uploading IMG_20230703_103439.jpg…]()

Event's card sections @Susmita-Dey @prnvtripathi

**Comment by Susmita-Dey** [comment]
@Abhinavcode13 There's already an hover state on those cards. What do you want to implement there?
