### ISSUE TITLE
[BUG] Add image

### ISSUE THREAD

**Issue by shraddha761** [devs-in-tech/DevsInTech#324]
### Is there any existing issue for this?

- [X] I have searched the existing issues

### Description

Add image to right side of main page to cover blank space

### Screenshots

![image](https://github.com/devs-in-tech/DevsInTech/assets/106100728/0a1aa1ee-9a3f-4eee-99e6-844e1a82888e)

### Any additional information?

assign this issue to me under GSSOC'23

**Comment by Susmita-Dey** [comment]
Hey @shraddha761 What kind of image you wanna add here?

**Comment by shraddha761** [comment]
@Susmita-Dey I'll give you some suggestions then you choose what to add

**Comment by prnvtripathi** [comment]
any updates @shraddha761 ?

**Comment by shraddha761** [comment]
@prnvtripathi this issue is not assigned to me so I thought it didn't require
