### ISSUE TITLE
[OTHER] Text in Features is not properly align

### ISSUE THREAD

**Issue by Prajwal0225** [devs-in-tech/DevsInTech#328]
### What would you like to share or ask?

**The text in the Features section is not properly aligned it does not look good.**

![image](https://github.com/devs-in-tech/DevsInTech/assets/103810119/569171a2-957d-4734-a687-1dd13e230624)

I would like to work on this issue and align it properly.

**Comment by Susmita-Dey** [comment]
#311 pullrequest already solves this issue.
