### ISSUE TITLE
Request to Add Search Functionality in Event Section ⚡

### ISSUE THREAD

**Issue by Nishitbaria** [devs-in-tech/DevsInTech#349]
### What would you like to share or ask?

>  **I often find myself browsing the Event section of the community website to discover upcoming events, workshops, and conferences. However, as the number of events grows, it becomes increasingly challenging to locate specific events based on criteria such as topic, date, or location. Therefore, I would like to request the addition of a search functionality to improve the user experience and make it easier to find relevant events.**

### Additional information

Expected Behavior:

- I kindly request the implementation of a search functionality in the Event section of the DevinTech community website. This feature should enable community members to search for events based on various criteria, including but not limited to:
- Keywords: Users should be able to search for events by entering specific keywords related to the event title, topic, speaker, or any other relevant information.
- Date Range: Users should have the ability to search for events within a specific date range, allowing them to find events that match their availability or interest during a particular time period.
- Location: It would be beneficial to include a search option to filter events based on location. This would allow users to find events happening in their city, region, or country, facilitating local engagement.
- Tags or Categories: Incorporating tags or categories associated with events would enable users to search for events that fall under specific topics of interest, making event discovery more efficient.

**Comment by Susmita-Dey** [comment]
Hey @Nishitbaria Great idea

**Comment by Nishitbaria** [comment]
@Susmita-Dey ,please review and merge my pull request
