### ISSUE TITLE
Newsletter Component for DevinTech Community Website ⚡

### ISSUE THREAD

**Issue by Nishitbaria** [devs-in-tech/DevsInTech#351]
### **Please feel free to ask for any clarifications or further details regarding this issue  :)**

**Comment by Nishitbaria** [comment]
Yes @Susmita-Dey 
![image](https://github.com/devs-in-tech/DevsInTech/assets/85815172/eac348c3-b409-4741-af9e-4c14a79f6ce5)

**Comment by Nishitbaria** [comment]
@Susmita-Dey ,do you want me to create separate page or in an component?

**Comment by Nishitbaria** [comment]
> @Susmita-Dey ,do you want me to create separate page or in an component? This is current status:(the news letter is working ) ,tell me where do you want newsletter ? ![image](https://user-images.githubusercontent.com/85815172/251428177-5490885d-df46-4d93-bd97-670454e154de.png)

**Comment by Susmita-Dey** [comment]
I just need the newsletter component to add at the end of the landing page above the footer

**Comment by Nishitbaria** [comment]
> I just need the newsletter component to add at the end of the landing page above the footer

ok,I will create pull request asap

**Comment by Nishitbaria** [comment]
@Susmita-Dey ,I have made pull request ,please review and merge
