### ISSUE TITLE
[BUG] Website is not responsive for mobile device

### ISSUE THREAD

**Issue by Nehagaddam2909** [devs-in-tech/DevsInTech#353]
### Description

The components of the websites are not properly aligned on the mobile device

### Screenshots

![image](https://github.com/devs-in-tech/DevsInTech/assets/47719476/986db86d-eb34-4104-bc04-63e6f482539b)

### What browser are you seeing the problem on?

Chrome, {"label"=>"I am a GSSoC'23 contributor", "required"=>false}

**Comment by Susmita-Dey** [comment]
If you think that, you wanna work on only the stat section, then it's a duplicate issue which has been already solved. In that case, kindly close this issue
