### ISSUE TITLE
Hero section Improvement

### ISSUE THREAD

**Issue by ShreyaDhiman24** [devs-in-tech/DevsInTech#358]
### What would you like to share or ask?

![image](https://github.com/devs-in-tech/DevsInTech/assets/98320971/06c6c774-e3ee-453b-893f-c2c095d0d006)

Adding beautiful graphic can make website look more good. Wish to work under GSSoC'23

**Comment by karantec** [comment]
please assign me this issue i will solve under GSSOC'23
