### ISSUE TITLE
[SECTION] Footer section re-design - Sample design is given!

### ISSUE THREAD

**Issue by Varghab** [devs-in-tech/DevsInTech#361]
### What would you like to share or ask?

Hello @Susmita-Dey , The footer section is not properly visible. Please assign me the issue under GSSoC'23.
**I really want to create a footer section for DevsinTech, I have already made a similar contribution for vibey -** 

![Screenshot 2023-06-29 163133](https://github.com/devs-in-tech/DevsInTech/assets/59419650/5c2d3c07-6372-4acc-b194-ed2b894d694f)

![Screenshot 2023-06-29 163204](https://github.com/devs-in-tech/DevsInTech/assets/59419650/b0d8d752-e552-41cc-9b1b-8273eeb07853)

![Screenshot 2023-06-29 163232](https://github.com/devs-in-tech/DevsInTech/assets/59419650/9baa672c-77d9-4eec-bed8-bbe2af1e8cab)

**Current Footer -** 

![Screenshot 2023-07-06 141722](https://github.com/devs-in-tech/DevsInTech/assets/59419650/a30aff5d-4344-426e-9b8c-9bc6ce58410b)

**Comment by prnvtripathi** [comment]
Go ahead! assigning this to you.
