### ISSUE TITLE
[REDESIGN] MenuBar re-design - I have provided the sample design!

### ISSUE THREAD

**Issue by Varghab** [devs-in-tech/DevsInTech#362]
### What would you like to share or ask?

With all due respect to the developer who created the current menubar, the menuBar looks decent but I can make it even better. I have created multiple menuBar in the past. Please refer to my recent work for Vibey - 

![Screenshot 2023-06-24 053403](https://github.com/devs-in-tech/DevsInTech/assets/59419650/7d60e3aa-ec0c-41f9-a63d-76d1dbd681d6)
![Screenshot 2023-06-24 053417](https://github.com/devs-in-tech/DevsInTech/assets/59419650/b0b01f36-5baa-495f-9721-7ca739afda28)

Please assign me the issue under GSSoC, I am really looking forward to create a elegant menuBar for DevsInTech.

**Comment by prnvtripathi** [comment]
@Susmita-Dey and @devs-in-tech/devsintech-web-team look into the issue and design

**Comment by Gauravbisht231** [comment]
Are they really assigning issues to contributors or not. I can not see much assignments from owner's side
@Varghab @prnvtripathi

**Comment by Varghab** [comment]
@Gauravbisht231 @prnvtripathi I want to work on this issue, please have a look!

**Comment by prnvtripathi** [comment]
@Susmita-Dey Please have a look
