### ISSUE TITLE
[FEATURE] What members say about us, transition to one another can be smooth.

### ISSUE THREAD

**Issue by Sar-thak-3** [devs-in-tech/DevsInTech#363]
### What would you like to share or ask?

The transition in the section "What members say about us"  can be smooth, it's not looking good currently as it shows transition without any delay and no CSS. 

### Additional information

![image](https://github.com/devs-in-tech/DevsInTech/assets/100359818/cce52444-ee5e-48b4-b357-35543cb65b4d)

**Comment by prnvtripathi** [comment]
@Sar-thak-3 Go on assigning this issue to you.
