### ISSUE TITLE
Team member design enhancement 

### ISSUE THREAD

**Issue by I-shika** [devs-in-tech/DevsInTech#365]
### What would you like to share or ask?

In teams section  ui can be more attractive by hiding the social media handles of every member without hover and on hovering the name will be uplifted and the handles will appear.

I think this enhancement will make it better.

Please assign this issue to me under GSSoC'23.

**Comment by karantec** [comment]
please assign me this issue i will solve under GSSOC'23

**Comment by prnvtripathi** [comment]
@I-shika can you share some example or design on how do you plan on changing the UI

**Comment by prnvtripathi** [comment]
@karantec, Please look for any other issue. Thank you for contributing.

**Comment by I-shika** [comment]
yes @prnvtripathi  the following image shows the ui in which first image is without hover and second one is on hover.
I want to do it in same way.
![Screenshot (123)](https://github.com/devs-in-tech/DevsInTech/assets/100770197/3253a47a-f9d7-466a-b92a-246e07536a24)

**Comment by prnvtripathi** [comment]
Go ahead, assigning this to you.
