### ISSUE TITLE
Improving the FAQ section

### ISSUE THREAD

**Issue by Illaf** [devs-in-tech/DevsInTech#370]
### What would you like to share or ask?

The FAQ section can be redesigned so that it looks more good and impressive
Please assign this issue so that I can redesign it and if you like then you may merge it.

**Comment by prnvtripathi** [comment]
How do you plan on improving the design, can you show an example.

**Comment by Illaf** [comment]
> How do you plan on improving the design, can you show an example.

I am preparing the design,nwill show you soon

**Comment by Illaf** [comment]
@Susmita-Dey  @prnvtripathi please check the new design
![Screenshot (60)](https://github.com/devs-in-tech/DevsInTech/assets/114517448/f8d1572c-0723-47c8-9fd5-c65d5738e5ec)

![Screenshot (61)](https://github.com/devs-in-tech/DevsInTech/assets/114517448/b2e50f0b-1ed6-4ac2-9006-0633d2c673ca)

**Comment by prnvtripathi** [comment]
Go ahead, assigning this to you.

**Comment by Illaf** [comment]
> Go ahead, assigning this to you.

okay👍
