### ISSUE TITLE
Improve cards of contributor's page

### ISSUE THREAD

**Issue by Shivam-Katare** [devs-in-tech/DevsInTech#372]
### What would you like to share or ask?

The `contributor's page` has big cards which do not look good in UI. I want to improve the cards of the `contributors page` so that, it will look much cleaner and easy to read.

### Additional information

Currently, the cards are too big, which does not look good.

![Screenshot (1029)](https://github.com/devs-in-tech/DevsInTech/assets/91705825/0b5dd9b2-764f-4cdd-bdd8-1a493d2cfa8a)

**Comment by prnvtripathi** [comment]
@Shivam-Katare can you share any design, about how would you like to change the UI

**Comment by Shivam-Katare** [comment]
> @Shivam-Katare can you share any design, about how would you like to change the UI

@prnvtripathi I am looking for this design. It has smooth transactions and UI as compared to the current card UI. Although the height of the cards we can reduce according to the need. What is your thought?

![Untitled design](https://github.com/devs-in-tech/DevsInTech/assets/91705825/d06b7e99-83eb-4dc1-8b08-c339522c298e)

**Comment by prnvtripathi** [comment]
Looks cool, start working on it..
