### ISSUE TITLE
[BUG] <Adding light mode>

### ISSUE THREAD

**Issue by Shreya111111** [devs-in-tech/DevsInTech#373]
### Is there any existing issue for this?

- [X] I have searched the existing issues

### Description

As this website is already in dark mode wanted to apply light mode. this will be applicable to all the pages

### Any additional information?

I am gssoc'23 contributer

**Comment by Shreya111111** [comment]
@Susmita-Dey  kindly assign this to me

**Comment by prnvtripathi** [comment]
hey @Shreya111111, this is feature isn't planned right now. Thank you for rasing an issue.
