### ISSUE TITLE
[Docs]: updating docs

### ISSUE THREAD

**Issue by Shreya111111** [devs-in-tech/DevsInTech#374]
### what's wrong in the documentation?

changes to be made
We need to add the installation procedure via pnpm/npm and also with docker. It will help user to understand how to do project setup.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I am a GSSoC'23 contributor

**Comment by prnvtripathi** [comment]
Go on and start working on this issue.
