### ISSUE TITLE
Add GitHub link in footer section.

### ISSUE THREAD

**Issue by blindaks** [devs-in-tech/DevsInTech#378]
### What would you like to share or ask?

I want to add a GitHub link in the footer section.
![Screenshot (35)](https://github.com/devs-in-tech/DevsInTech/assets/128223364/de091ab4-32ab-455d-981f-ecf2eead707a)

**Comment by prnvtripathi** [comment]
Go ahead.

**Comment by blindaks** [comment]
@prnvtripathi Please review my PR.

**Comment by blindaks** [comment]
@prnvtripathi Please close this issue so that it can be counted as a contribution in GSSOC
