### ISSUE TITLE
[OTHER] add issue templates 

### ISSUE THREAD

**Issue by priyankarpal** [devs-in-tech/DevsInTech#38]
### What would you like to share or ask?

We have to add a few issue templates for separate issues

I want to work on it

**Comment by AbhiPatel10** [comment]
We already have issue templates which type of template you want to add ? Please give some more information.

**Comment by priyankarpal** [comment]
> We already have issue templates which type of template you want to add ? Please give some more information.

currently, there are only three templates we have to add more like docs, style etc.

![image](https://user-images.githubusercontent.com/88102392/236609846-771edb9b-a1cf-4313-9563-5768b402a50b.png)

**Comment by AbhiPatel10** [comment]
Okay got it nice idea, @priyankarpal go ahead
