### ISSUE TITLE
[BUG]: HEADER BACKGROUND ERROR DURING SCROLL 🪲

### ISSUE THREAD

**Issue by 0xabdulkhalid** [devs-in-tech/DevsInTech#380]
### Is there any existing issue for this?

- [X] I have searched the existing issues

### Description

- The header's background seems to be not well applied during the scrolling of page.
- The `ul` element has a separate background contrast to the header's background contrast.
- We need to fix this misinterpretation by applying right style rules to fix this Bug.

### Screenshots

![image](https://github.com/devs-in-tech/DevsInTech/assets/92252895/c0a6f1bd-4f2a-4207-b2bc-ac787d19b728)

### What browser are you seeing the problem on?

Firefox

**Comment by 0xabdulkhalid** [comment]
Hey there @prnvtripathi 👋🏻

Please make sure to assign this issue to me asap to make the work done!

Thank you.

**Comment by prnvtripathi** [comment]
@0xabdulkhalid I am unable to see this issue in my browser, but I'm assigning this to you.
