### ISSUE TITLE
[OTHER]Revamp ui of the Events page routed on the navbar

### ISSUE THREAD

**Issue by karthiknadar1204** [devs-in-tech/DevsInTech#381]
### What would you like to share or ask?

I looked out for a similar issue, couldn't find one.
The proposed changes are:
- The main heading at the top of the page, we could push it to the left,reduce the font weight and increase the font size for both the heading and the text it holds.
- For the features,We could push the section as a whole to the right, the Features heading and the text it holds should be put in a container and text align left again to align the text in one line.
- For the blogs,I was thinking of having an overlay effect on hovering, for reference, please refer to this link, the hover on the blog here in this link is what I am suggesting for out project.
https://umatter-eight.vercel.app/#/blogs

### Additional information

Just another suggestion, how about we add the Tw heading, the one on the top and the Features heading in a light-coloured container and then push them to the left and right side respectively with the appropriate border-radius?
Also thought of adding some border-radius to these containers and animation effects like when we open the page for the first time, the contents of the page fade in from the left and right side slowly.

Please feel free to share your views, will try adding those styles as well

**Comment by karthiknadar1204** [comment]
I would like to work on this issue under gssoc'23

**Comment by prnvtripathi** [comment]
Go ahead I'm assigning this to you.

**Comment by karthiknadar1204** [comment]
Thank you, will get working on it

**Comment by karthiknadar1204** [comment]
SORRY FOR THE DELAY, HAVE BEEN EXTREMELY BUSY WITH COLLEGE EXAMS, WILL WRAP UP THIS WEEKEND

**Comment by prnvtripathi** [comment]
Sure take your time
