### ISSUE TITLE
[Feature] add dependabot gh action

### ISSUE THREAD

**Issue by priyankarpal** [devs-in-tech/DevsInTech#40]
### Description

we are using npm dependencies & also using gh actions so if we add the dependabot gh action we don't need to update dep & gh actions manually.

dependabot will update these automatically by creating the PR

I want to work on this issue

**Comment by AbhiPatel10** [comment]
New Updates may introduce breaking changes or compatibility issues.

**Comment by priyankarpal** [comment]
ok then we should close this PR.
