### ISSUE TITLE
[BUG]: HEADER BACKGROUND 🪲

### ISSUE THREAD

**Issue by 0xabdulkhalid** [devs-in-tech/DevsInTech#405]
### Is there any existing issue for this?

- [X] I have searched the existing issues

### Description

- The header's background color is much more opac and allows the content to be overlapped.
- This affects the accessibility, and cause strains to users.
- We need to provide much more solid background or we can just increase the bg opacity a little bit to fix this problem

### Screenshots

![Screenshot 2023-07-19 at 19-55-00 https __devsintech vercel app](https://github.com/devs-in-tech/DevsInTech/assets/92252895/2bbcde2b-9049-4d90-9237-2ec4c6616f4b)

### What browser are you seeing the problem on?

Firefox

**Comment by prnvtripathi** [comment]
the header is on purpose made translucent, by the thank you for raising this issue.

**Comment by prnvtripathi** [comment]
Close this issue if you don't want to change anything else in the header
