### ISSUE TITLE
[OTHER] Improving SEO by adding meta tags to pages

### ISSUE THREAD

**Issue by tayyab-ilyas** [devs-in-tech/DevsInTech#434]
### What would you like to share or ask?

For better SEO, we need to implement meta tags. They play a crucial role in providing search engines with essential information about our web pages, helping them understand the content and relevance of each page. By adding meta tags such as page titles, descriptions, keywords, and canonical URLs, we can enhance our website's visibility in search engine results and improve organic traffic.

**Comment by tayyab-ilyas** [comment]
hey @Susmita-Dey can you assign this to me under Gssoc'23? thanks!

**Comment by Susmita-Dey** [comment]
Hey @tayyab-ilyas Have you checked for existing issues?

**Comment by tayyab-ilyas** [comment]
> Hey @tayyab-ilyas Have you checked for existing issues?

yes
