### ISSUE TITLE
[Feature] <bgcolor change on hover>

### ISSUE THREAD

**Issue by jayk-gupta** [devs-in-tech/DevsInTech#45]
### Description

Add bgcolor change on hover on buttons

### Screenshots

![Screenshot 2023-05-06 123729](https://user-images.githubusercontent.com/100681165/236608938-ef7ccfa6-1a80-4f0f-b5c3-7561fdae44a3.png)

**Comment by AbhiPatel10** [comment]
Hey @jayk-gupta Are you working on it ?

**Comment by jayk-gupta** [comment]
yes

**Comment by AbhiPatel10** [comment]
Then make a pr

**Comment by jayk-gupta** [comment]
Sent PR
