### ISSUE TITLE
[OTHER] Critical Accessibility Issues

### ISSUE THREAD

**Issue by nfa1** [devs-in-tech/DevsInTech#53]
### What would you like to share or ask?

Hi Devs Team! I ran the website through accessibilitychecker.org which found 7 critical accessibility issues as starting points for improvement: 

1. Visual & motor | [accesskey] values are unique.
2. Visual issue | Background and foreground colors do not have a sufficient contrast ratio.
3. Visual issue | ARIA IDs are unique.
4. Visual & motor | <frame> or <iframe> elements have a title.
5. Visual issue | <html> element does not have a [lang] attribute.
6. Visual issue | Form elements have associated labels.
7. Visual issue | Links do not have a discernible name.

Attached below is the full accessibility audit report for reference:

[devsintech.netlify.app-05.12.2023.pdf](https://github.com/devs-in-tech/DevsInTech/files/11466797/devsintech.netlify.app-05.12.2023.pdf)

### Additional information

Please let me know if you have any questions or feedback. I am also open to helping out on some of these issues as well as collaborating with other team members. Thanks!

**Comment by AbhiPatel10** [comment]
Thank you for checking accessibility, but we are just building the website; when it is complete, we will check accessibility again and improve it.

If you would like to work please check https://devsintech.netlify.app/ and raise other issues.
