### ISSUE TITLE
Create /team page and show all the contributers there

### ISSUE THREAD

**Issue by abdulmoizsheraz** [devs-in-tech/DevsInTech#61]
### Description

Create /team page and show all the contributers there

**Comment by AbhiPatel10** [comment]
Yes we are working on design of team page, do you like to contribute in design (figma)?

**Comment by prnvtripathi** [comment]
> I would like to develop the page I am not designer

We'll let you know about it :)
Happy contributing

**Comment by Sayan2k3** [comment]
Hey as a contributor of GSSOC'23 ,I want to work with the project .Assign me the issue

**Comment by syedawanya18** [comment]
I want to work on this issue
Pleasure Assign so that I can show my skills under GSSoC'23.

**Comment by Tushar98644** [comment]
@AbhiPatel10 @himanshu1221 is the design ready ?

**Comment by AbhiPatel10** [comment]
> @AbhiPatel10 @himanshu1221 is the design ready ?

Not yet, Work in progress

**Comment by Phyozawhein** [comment]
Hi, I'd like to help. Could I get assigned to this issue ? Thank you !

**Comment by KamalSritha-04** [comment]
Can you please assign me this issue under GSSOC'23?

**Comment by AbhiPatel10** [comment]
Guys basic layout of teampage is ready once it live i will ask you to make changes on that page

**Comment by himanshu1221** [comment]
closing this issue as this issue has been resolved
