### ISSUE TITLE
The Website content is not centered properly

### ISSUE THREAD

**Issue by abdulmoizsheraz** [devs-in-tech/DevsInTech#65]
### Is there any existing issue for this?

- [X] I have searched the existing issues

### Description

The Website is not responsive content is not centered 
See space on the right side

### Screenshots

![Screenshot_2023-05-14-21-33-34-88](https://github.com/devs-in-tech/DevsInTech/assets/132380648/407db1f5-bc67-4449-9de6-da0be5f9709f)
![Screenshot_2023-05-14-21-33-24-05](https://github.com/devs-in-tech/DevsInTech/assets/132380648/ce3683a2-8864-40ab-b693-f57ba0e70b31)
![Screenshot_2023-05-14-21-33-19-14](https://github.com/devs-in-tech/DevsInTech/assets/132380648/fb733caf-0e8e-441a-b7da-50c4f26fc480)

### What browser are you seeing the problem on?

Chrome

**Comment by abdulmoizsheraz** [comment]
Also Assigne this issuse to me

**Comment by AbhiPatel10** [comment]
@abdulmoizsheraz go ahead
