### ISSUE TITLE
[OTHER] remove `package-lock.json`

### ISSUE THREAD

**Issue by priyankarpal** [devs-in-tech/DevsInTech#66]
### What would you like to share or ask?

We are using `pnpm` for this project & it's recommended to use one package manager for a particular project. So, we need to remove the `package-lock.json` file & also need to add it to the `.gitignore` file.

- We need to mention to the docs to use only `pnpm` for this project. 
- also, we need to mention that if your system hasn't installed `pnpm`, you need to install it using the `npm install -g pnpm`

### I want to work on this issue. 

![image](https://github.com/devs-in-tech/DevsInTech/assets/88102392/443c5645-7079-44ed-92b9-6cde8ee31d86)

**Comment by Shubh8899** [comment]
I would like to work on this one.

**Comment by priyankarpal** [comment]
Assign me to do this work
