### ISSUE TITLE
[Docs]: improve `README.md` & `CONTRIBUTING.md` files

### ISSUE THREAD

**Issue by priyankarpal** [devs-in-tech/DevsInTech#67]
### what's wrong in the documentation?

Now in these `README.md` & `CONTRIBUTING.md` two docs files, there are no proper guides for this project's use cases. we need to add step-by-step best practices.  

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AbhiPatel10** [comment]
Go ahead @priyankarpal

**Comment by priyankarpal** [comment]
@AbhiPatel10 please unassign me currently I'm not getting enough time to complete this task sorry for that. You can assign another person.

**Comment by TanmayAdithya** [comment]
> Okay

Hope you had a great day @AbhiPatel10! I have prior experience in enhancing documentation. I have created the CONTRIBUTING.md file for [Love Simple UI](https://github.com/thekavikumar/love-simple-ui). I'd love to volunteer in contributing to this issue if you are comfortable to assign.

 - [x] I agree to follow this project's Code of Conduct
 - [x] I have read the contribution guidelines
 - [x] I will keep the project maintainer updated with my progress on the issue and seek help If I face any issue

**Comment by TanmayAdithya** [comment]
Hi @AbhiPatel10 ,

I wanted to provide you with an update on the progress I've made regarding the documentation issue I'm currently working on. Here are the details:

- Changes made so far to CONTRIBUTING.md:
 

- [x] Added resources for new contributors to get familiar with Git & GitHub  
- [x] Added a section explaining how contributors can fork their project along with images
- [x] Added a section explaining how to create a new issue for Bug Report, Documentation Issue, Style Change and Feature Request.
- [x] Incorporated commands and screenshots related to creating a branch and committing changes.


- Next Steps:
  - [ ] Add a section instructing how to solve existing issues
  - [ ] Add a section instructing how to create a good PR
  
I would appreciate any feedback or guidance you may have regarding my progress so far. Let me know if there are any specific areas I should focus on or if there are any resources I should refer to. I'm committed to delivering high-quality documentation that improves the user experience and supports the project's goals.

Thank you for your support and guidance throughout this process. I look forward to your feedback. 

Also a quick side note, this issue wasn't assigned any level, so assigning a level would help me move up on the leader board. 

Best regards,
Tanmay Adithya
