### ISSUE TITLE
[style]: Update Footer

### ISSUE THREAD

**Issue by Amank-root** [devs-in-tech/DevsInTech#69]
### What's the style idea?

The UI of the footer is way too off and especially the color of the text in some places is nearly invisible due to submerging background. I have attached the screenshot of the current footer which is not up to the mark. Assign the issue to me so that I can resolve it.

### Add screenshots

Add screenshots
![image](https://github.com/devs-in-tech/DevsInTech/assets/70597017/4bc7dbe1-4d36-4805-974c-0191ac655d76)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by AbhiPatel10** [comment]
Go ahead.

**Comment by dhrumishah** [comment]
> Go ahead.

What's the update on this issue? 

I would like to work on it.
Thanks

**Comment by AbhiPatel10** [comment]
Hey @Amank-root, Have completed this issue ? if not let us know or we will give this issue to another contributors.

**Comment by dhrumishah** [comment]
> Hey @Amank-root, Have completed this issue ? if not let us know or we will give this issue to another contributors.

I think so he is not active. Can you please pass this issue to me?

**Comment by Amank-root** [comment]
> Hey @Amank-root, Have completed this issue ? if not let us know or we will give this issue to another contributors.

Sorry for being inactive for a week actually I have my exams going on which will end tomorrow so by 26th I'll resolve the issue.

**Comment by himanshu1221** [comment]
no worries @Amank-root take your time
