### ISSUE TITLE
[BUG]Scroll To Navbar links [GSSoC'23]

### ISSUE THREAD

**Issue by Sukhendu2002** [devs-in-tech/DevsInTech#74]
### Is there any existing issue for this?

- [X] I have searched the existing issues

### Description

Navbar links are not working
Can you assign this issue to me, I want to work on this

### What browser are you seeing the problem on?

Microsoft Edge

**Comment by shreverr** [comment]
Please assign this to me!

**Comment by shreverr** [comment]
I have fixed the About us link but the pages directory does not have any page for events and team

**Comment by himanshu1221** [comment]
hey @Sukhendu2002 we are working on the `teams` page 
You can refer to this issue for further discussion #61 
If you have any design in your mind you can share it in that issue so it will not create any chaos

Rest you can add a scroll feature for the `home`,`about` and `events` page

**Comment by Sukhendu2002** [comment]
Thank you, @himanshu1221, for assigning this issue to me. I will begin working on it promptly.
