### ISSUE TITLE
[style]: Improve the footer

### ISSUE THREAD

**Issue by karthiknadar1204** [devs-in-tech/DevsInTech#75]
### What's the style idea?

We need to improve  improve the footer by spreading the links across three different rows with abundant spacing between them

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by karthiknadar1204** [comment]
I would like to work on this issue under gssoc'23

**Comment by karthiknadar1204** [comment]
The footer links can be spread across three rows and one fourth row with the favicons for the social links and the logo for the project at the top left corner of the footer and the copyright statement at the bottom of the footer in the middle and the purpose of the project under the logo occupying one line

**Comment by karthiknadar1204** [comment]
@himanshu1221 How does the solution sound?

**Comment by himanshu1221** [comment]
hey @karthiknadar1204 we assign one issue at a time 
This issue is relevant enough So Not closing it 
let others also get their hands dirty on this Project:wink:

**Comment by karthiknadar1204** [comment]
Ah sure it's fine,I'll finish my share of issues and jump to new ones

**Comment by himanshu1221** [comment]
This issue already exists #69
