### ISSUE TITLE
[style]: improve the button stying by adding some more styling like a good hover effect and changing the favicon used

### ISSUE THREAD

**Issue by karthiknadar1204** [devs-in-tech/DevsInTech#76]
### What's the style idea?

We need to improve  improve the button stying by adding some more styling like a good hover effect and changing the favicon used

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by karthiknadar1204** [comment]
I would like to work on this issue under gssoc'23

**Comment by Tushar98644** [comment]
I would like to take up the issue @himanshu1221

**Comment by himanshu1221** [comment]
Go for it @Tushar98644 
Assinging ypu 🚀

**Comment by syedawanya18** [comment]
I want to work on this issue as a contributor.
Pleasure Assign so that I can show my skills under GSSoC'23.

**Comment by thisnotebook** [comment]
Hey there, I am Interested to change buttons by improving the styling of buttons  and 
New issue :- "home-about us-events-team" are in between on the screen and in small devices like mobile it not correctly at center I personally feel if 3 lines in mobile device in right side so  "home-about us-events-team" section also at the right side of screen. Here is example
![3lines](https://github.com/devs-in-tech/DevsInTech/assets/99406469/6498c72c-b31a-4f75-b0bf-c91ec9777888)
So assign me to fix that...

**Comment by AbhiPatel10** [comment]
Icons and hover effect is already done on buttons
