### ISSUE TITLE
[BUG] Fixing the accordion

### ISSUE THREAD

**Issue by karthiknadar1204** [devs-in-tech/DevsInTech#77]
### Is there any existing issue for this?

- [X] I have searched the existing issues

### Description

Right now when we have opened one accordion,we can simultaneously open another accordion while the first one is still open,we should add a styling feature wherein we can open only one accordion at a time and when opening another accordion,the first one closes automatically

### What browser are you seeing the problem on?

Chrome

**Comment by karthiknadar1204** [comment]
I would like to work on this issue under gssoc'23

**Comment by himanshu1221** [comment]
Go Ahead @karthiknadar1204 assigning you :rocket:

**Comment by karthiknadar1204** [comment]
Sure thank you

**Comment by karthiknadar1204** [comment]
Have started the work on this issue @himanshu1221 ,buggy with the logic,will keep you updated

**Comment by himanshu1221** [comment]
> Have started the work on this issue @himanshu1221 ,buggy with the logic,will keep you updated
sure you can ping @Aadarsh805 for the same!

**Comment by karthiknadar1204** [comment]
@Aadarsh805 I have resolved the issue of opening a single accordion at a time, fixed the bug that hindered yesterday
<img width="1745" alt="Screenshot 2023-05-22 at 9 40 46 AM" src="https://github.com/devs-in-tech/DevsInTech/assets/95973644/1d9cbf45-92d5-4590-a22c-a9392a8a480f">






I am trying to push my changes but it is showing this error
<img width="1073" alt="Screenshot 2023-05-22 at 9 48 18 AM" src="https://github.com/devs-in-tech/DevsInTech/assets/95973644/73caaca8-75bb-4f2a-9875-fa83cea663b6">

How do i proceed

**Comment by karthiknadar1204** [comment]
fixing the bug, will keep you updated
Thank you

**Comment by AbhiPatel10** [comment]
> @Aadarsh805 I have resolved the issue of opening a single accordion at a time, fixed the bug that hindered yesterday <img alt="Screenshot 2023-05-22 at 9 40 46 AM" width="1745" src="https://user-images.githubusercontent.com/95973644/239801858-1d9cbf45-92d5-4590-a22c-a9392a8a480f.png">
> 
> I am trying to push my changes but it is showing this error <img alt="Screenshot 2023-05-22 at 9 48 18 AM" width="1073" src="https://user-images.githubusercontent.com/95973644/239801932-73caaca8-75bb-4f2a-9875-fa83cea663b6.png">
> 
> How do i proceed

You need to add subject in commit message, you can check previous commits to know better.
