### ISSUE TITLE
[style]: Improved Social media links and Toggle button for Dark mode.

### ISSUE THREAD

**Issue by Nikhil1017** [devs-in-tech/DevsInTech#79]
### What's the style idea?

1) Place all the Social media links in the Header right side by replacing all the buttons with Social Media Icons.
2) Add a Toggle Button between Dark Mode and Light Mode.

### Add screenshots

SImilar to this

![image](https://github.com/devs-in-tech/DevsInTech/assets/115337705/dc05b1be-637a-4e1a-9676-739ba2a81e98)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by himanshu1221** [comment]
Go for it @Nikhil1017 assigning you :rocket:

**Comment by Nikhil1017** [comment]
Thanks 👍

**Comment by AbhiPatel10** [comment]
We do not need dark mode so closing this issue
