### ISSUE TITLE
[Feature] : Adding Light Mode

### ISSUE THREAD

**Issue by dev-AshishRanjan** [devs-in-tech/DevsInTech#81]
### Description

This project only has dark mode. 
so, I wanted to create a light mode theme using the dark mode theme.
And wanted to create Theme Toogle button.

**Comment by dev-AshishRanjan** [comment]
I wanted to work on this issue so, can you assign it to me under GSSoC'23

**Comment by himanshu1221** [comment]
hey @dev-AshishRanjan 
Can you share any designs?

**Comment by dev-AshishRanjan** [comment]
> hey @dev-AshishRanjan Can you share any designs?

For design purpose you may visit my portfolio - http://krashish.live/

Using css variable three modes are created : 
- system ( Default)
- Dark
- Light

And we have a button/ dropdown to toggle modes.

**Comment by dev-AshishRanjan** [comment]
Hi @himanshu1221 ,
If you are going to accept this issue,
Then please notify me or assign me this issue
so I can work on this issue.

**Comment by AbhiPatel10** [comment]
As we are not planning to add light and dark mode functionality so i'm closing this issue
