### ISSUE TITLE
[Feature] Adding a back to top button

### ISSUE THREAD

**Issue by suryanshsoni120** [devs-in-tech/DevsInTech#82]
### Description

If the user wishes to go back to top from any section, it would be better if there is a button to navigate to top directly. I would like to contribute to this issue under GSSOC'23. Please assign me this issue.

**Comment by himanshu1221** [comment]
Can you share any design if any ?

**Comment by suryanshsoni120** [comment]
![Feature demo](https://github.com/devs-in-tech/DevsInTech/assets/63662732/7df17a9a-96d7-4eba-9c2d-a37b969cf0b8)

**Comment by himanshu1221** [comment]
Awesome LGTM:+1:
assigning you :rocket: 
Waiting for your PR
