### ISSUE TITLE
[Update] Update the text in hero section 

### ISSUE THREAD

**Issue by himanshu1221** [devs-in-tech/DevsInTech#83]
### What would you like to share or ask?

Updating the text in the hero section

![Screenshot from 2023-05-20 20-34-40](https://github.com/devs-in-tech/DevsInTech/assets/32031706/4c9175ec-abd6-4f29-962c-4838d0b1d387)

**Comment by kalanal** [comment]
Hi, I would like to take this up and work on it. Thanks!

**Comment by syedawanya18** [comment]
I want to work on this issue as a contributor.
Pleasure Assign so that I can show my skills under GSSoC'23.
