### ISSUE TITLE
feat : updates on landing page 

### ISSUE THREAD

**Issue by KaKashi1210** [devs-in-tech/DevsInTech#84]
### Description

I feel the empty space should be filled or  text should take up full space.

### Screenshots

![image](https://github.com/devs-in-tech/DevsInTech/assets/97914006/f243d27e-6299-44c6-b7c7-6dd0fa82002c)

**Comment by himanshu1221** [comment]
Any Ideas @KaKashi1210 ?

**Comment by KaKashi1210** [comment]
this repo uses framer motion right ? so it will be nice if we can use text animation that writes devs in tech community

**Comment by PatilHarshh** [comment]
Hello ,
I'm harsh. I want to work on this issue under Gssoc'23. I am really eager to work on open source projects and contribute to this community.I've taken a look at the codebase and I believe I can make some valuable improvements. I'll start working on it right away.

Skills
HTML5, CSS3, JS, Bootstrap | node js mongodb | Php, mysql | MERN | Responsive Design 

Can you please assign this issue to me.
@himanshu1221

**Comment by AbhiPatel10** [comment]
@KaKashi1210 Go ahead, just add little bit animation

**Comment by AbhiPatel10** [comment]
@KaKashi1210 Are you working on it ?

**Comment by KaKashi1210** [comment]
Im really sorry for replying late, i am busy with exams  can you please assign it to someone else.

**Comment by PatilHarshh** [comment]
@AbhiPatel10 please assign this to me i am interested....

**Comment by anuza08** [comment]
@AbhiPatel10 please assign this issue to me.
