### ISSUE TITLE
[Feature] Adding smooth scroll to the website

### ISSUE THREAD

**Issue by Mahitej28** [devs-in-tech/DevsInTech#85]
### Description

Hello, I am Mahima Churi, a proud contributor of GSSoc ' 23.

📌I would like to work on this project by adding a smooth-scroll feature to the website so that when we click on events or any other icon in the navbar it smoothly scrolls to that section.

📌Also, I would like to enhance the social media buttons by adding hover effects and animations along with their official icons

If you think it is legit then do assign me the issue under GSSoC '23 with the level of the PR as well

**Comment by himanshu1221** [comment]
hey @Mahitej28 someone is already working on enhancing social media icons `referred to this issue #79` you may proceed for Smooth scrolling
Best of luck :100:

**Comment by Mahitej28** [comment]
Ok I will proceed with adding a smooth-scroll feature, also for this some more items would be needed to added in the navbar basically the section heading that are there in homepage so that when click on it, it scrolls to that section on home page, so I would edit navbar also is that ok?

**Comment by himanshu1221** [comment]
> Ok I will proceed with adding a smooth-scroll feature, also for this some more items would be needed to added in the navbar basically the section heading that are there in homepage so that when click on it, it scrolls to that section on home page, so I would edit navbar also is that ok?

Someone is already working on this particular part navbar scrolling section so to avoid conflicts you first work with smooth scrolling feature

**Comment by Mahitej28** [comment]
Ok sure I will proceed

**Comment by himanshu1221** [comment]
> Ok sure I will proceed

Do join the Discord Channel if you are stuck somewhere

**Comment by Mahitej28** [comment]
From where can I get discord link?

**Comment by himanshu1221** [comment]
> From where can I get discord link?

From the website itself

**Comment by Mahitej28** [comment]
Will that be okay if I Contribute to this by the first week of June as my End Sems are starting tomorrow?

**Comment by himanshu1221** [comment]
> Will that be okay if I Contribute to this by the first week of June as my End Sems are starting tomorrow?

No worries all the best for your exams!
