### ISSUE TITLE
[Feature] Create a contact us page

### ISSUE THREAD

**Issue by An525ish** [devs-in-tech/DevsInTech#86]
### Description

I will create a contact us page with same theme so that people can reach to the author of the page in case of some query or feedback

**Comment by UditaVed** [comment]
I will be creating a page with fancy outlook according to the website's theme.

**Comment by himanshu1221** [comment]
hey @An525ish Do you have any design for this so that you can share with us & we can assign you

**Comment by An525ish** [comment]
yeah I do have ...it gonna look something like this....
![contact](https://github.com/devs-in-tech/DevsInTech/assets/93612051/f091b061-5581-423d-82f8-ed197948ec21)

**Comment by An525ish** [comment]
the theme would similar as of yours

**Comment by An525ish** [comment]
> 

the theme would be similar as of  your website

**Comment by An525ish** [comment]
> hey @An525ish Do you have any design for this so that you can share with us & we can assign you
...and the theme would be similar as of your website

**Comment by PARTH-1712** [comment]
I'm a contributor for GSSoC '23, I want to work on this issue. Please assign me.

**Comment by KamalSritha-04** [comment]
Can you please assign me this issue under GSSOC'23?

**Comment by oshinsaraf** [comment]
I could create a glassbox style contact us page and if possible a sign up page for this, please assign it to me under GSSOC'23.

**Comment by Kushagra102** [comment]
hey @himanshu1221 I would like to work on this issue under GSSOC23.
To create a the exact themed contact page. With mail functionality.

**Comment by Susmita-Dey** [comment]
Hey @An525ish Go ahead
