### ISSUE TITLE
[Feature] Adding a "Scroll to Top" Button

### ISSUE THREAD

**Issue by parthksingh1** [devs-in-tech/DevsInTech#88]
### Description

I would like to add a scroll to the top button. It will enchance the use Experience

**Comment by parthksingh1** [comment]
Please Assign me this under @GSSOC'23 to make it better

**Comment by parthksingh1** [comment]
Please Assign me this under @GSSOC'23 to make it better

**Comment by himanshu1221** [comment]
hey @parthksingh1 this issue already exists #82 
Before making any issue do heck the previous issue to prevent chaos
