### ISSUE TITLE
[BUG] Alignment issue on the Home Page.

### ISSUE THREAD

**Issue by abhinav-m22** [devs-in-tech/DevsInTech#89]
### Is there any existing issue for this?

- [X] I have searched the existing issues

### Description

As seen in the image below, there is not much spacing between the buttons and the headline which doesn't make a good apperance to the user.

### Screenshots

<img width="934" alt="image" src="https://github.com/devs-in-tech/DevsInTech/assets/113239388/f74c0db6-8703-4d0b-b3a0-bc974e012ee1">

### Any additional information?

I want to work on these issue. 
Please assign me the task under GSSoC'23.

### What browser are you seeing the problem on?

Chrome

**Comment by himanshu1221** [comment]
Looks good to me assigning you @abhinav-m22 :rocket:

**Comment by abhinav-m22** [comment]
I have made a PR. #99 
Please have a look.

**Comment by AbhiPatel10** [comment]
Merged
