### ISSUE TITLE
[Feature] Adding Hover Effects on the Card Components

### ISSUE THREAD

**Issue by abhinav-m22** [devs-in-tech/DevsInTech#90]
### Description

In the card component of the Latest Events Section, adding some hover effects and animations can improve the UX and a seamless experience to the user.
Image is attached below:

### Screenshots

<img width="853" alt="image" src="https://github.com/devs-in-tech/DevsInTech/assets/113239388/606dcdd3-4b4d-4390-beed-eb64d4694353">

### Additional Information

I want to work on these feature improvement.
Please assign me the task under GSSoC'23.

**Comment by UditaVed** [comment]
### **I will be adding subtle animations on the card like lifted up effect whenever someone hovers over it moreover the shape and size may also be modified according to theme of the website.**
![image](https://github.com/devs-in-tech/DevsInTech/assets/97843629/edf06aff-c628-42a9-8000-96d20ffd089b)
Would love to work on this feature.

**Comment by himanshu1221** [comment]
hey @abhinav-m22  we assign one issue at a time
This issue is relevant enough So Not closing it
let others also get their hands dirty on this Project :wink:

assigning you @UditaVed :rocket:

**Comment by AbhiPatel10** [comment]
Already done
