### ISSUE TITLE
[UPDATE] Discord server link is missing

### ISSUE THREAD

**Issue by Shalini469717** [devs-in-tech/DevsInTech#92]
### What would you like to share or ask?

![image](https://github.com/devs-in-tech/DevsInTech/assets/99305545/737d2c01-5201-4187-b33e-946d1e7d402b)

### Additional information

DevsIn Tech has a discord server, which is missing in the page. It can help more people join the server.

Can I work on this issue as part of gssoc?

**Comment by himanshu1221** [comment]
Looks relevant to me 
go for @Shalini469717 assigning you :rocket:
