### ISSUE TITLE
[Feature] Shimmer Effect

### ISSUE THREAD

**Issue by Prajuwal** [devs-in-tech/DevsInTech#93]
### Description
A shimmer effect can be added which will will display users some UI till the website loads completely.

### Screenshots

![shimmerdevtech](https://github.com/devs-in-tech/DevsInTech/assets/72605739/69dd6284-709d-40e7-a86a-278e2e1c09f5)

### Additional Information

Currently shows blank screen as seen in screenshot when loaded on slow speed of internet.
Would like to work on this

**Comment by Prajuwal** [comment]
Would like to work on this

**Comment by himanshu1221** [comment]
Hey @Prajuwal !
Can you share any video resources or any GIFs for the same so we can understand this issue more precisely?

**Comment by Tushar98644** [comment]
@Prajuwal I would like to take up the issue

**Comment by saiwali** [comment]
Hello @Prajuwal  I would like to work on this issue. I have little experience with the technologies needed so I feel I can make a valuable contribution to this repo. Can u assign this issue to me ??

**Comment by Prajuwal** [comment]
@himanshu1221 here in this video we can see that if speed of internet is slow , what user sees is a blank white screen.

https://github.com/devs-in-tech/DevsInTech/assets/72605739/9576b6ba-4220-4337-86c2-25a079cdf97e

**Comment by KamalSritha-04** [comment]
I want to work on this issue, Can you please assign it to me?

**Comment by AbhiPatel10** [comment]
Great, go ahead @Prajuwal
