### ISSUE TITLE
Content Not Visible

### ISSUE THREAD

**Issue by piyushkhurana2019** [devs-in-tech/DevsInTech#94]
### Is there any existing issue for this?

- [X] I have searched the existing issues

### Description

Here these texts/ options are not visible, i want to add beautiful styling to these .
<img width="1440" alt="Screenshot 2023-05-21 at 9 32 48 AM" src="https://github.com/devs-in-tech/DevsInTech/assets/96003210/5248b2e4-d5b6-41d5-8205-6f87ec349f6b">

### What browser are you seeing the problem on?

Chrome

**Comment by himanshu1221** [comment]
Hey there this issue has already been stated and someone is already working on it 
you can refer to #69 for the same
