### ISSUE TITLE
[style]: Footer needs change  [GSSOC 2023]

### ISSUE THREAD

**Issue by ManishaSwain8** [devs-in-tech/DevsInTech#96]
### What's the style idea?

We need to improve  the footer, it looks very simple and unorganised , 
I would like to work upon it make it better keeping color code of the website in mind.
please to assign it to me under GSSOC 2023 , changes will be done in no time. !

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by himanshu1221** [comment]
hey @ManishaSwain8 this issue has already been stated you can refer to #69 for the same
