### ISSUE TITLE
[style]: Animation to the cards in *Latest Events In DevsInTech* section  [GSSOC 2023]

### ISSUE THREAD

**Issue by ManishaSwain8** [devs-in-tech/DevsInTech#97]
### What's the style idea?

We need to improve ,

 Animation always adds an attractiveness to the website , the cards here need to be animated so as to look unique ,
I would like to work on this under GSSOC 2023 .
Please do assign it to me ,changes will be done in  no time !

### Add screenshots

Add screenshots

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by himanshu1221** [comment]
hey @ManishaSwain8 this issue has already been stated you can refer to #90 for the same
