### ISSUE TITLE
[style]: Add underline on hover on the buttons of navbar

### ISSUE THREAD

**Issue by piyushkhurana2019** [devs-in-tech/DevsInTech#98]
### What's the style idea?

We need to improve : The present hover effect on the navbar items seems to be incomplete. Please assign this task to me so that i can add a left to right underline effect on the items.
<img width="1440" alt="Screenshot 2023-05-21 at 12 23 12 PM" src="https://github.com/devs-in-tech/DevsInTech/assets/96003210/0df91121-f459-4b8d-ae0f-b2e908326648">

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by himanshu1221** [comment]
Looks relevant to me 
make the colour of underline gradient as the heading in the Hero section ie `Devs in tech community`
assigning you @piyushkhurana2019 :rocket:
